### ISSUE TITLE
Standard schema for JSON NeoVM tests

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo-vm#109]
As discussed with community, it would be useful to have standard test format to guarantee cross-compatible integration tests between projects.
I believe current JSON tests are very nice, and I have started to build a validation JSON schema for it. By doing that, some small ideas emerged to fix and clarify details.

Right now, the following draft can already be validated:
```json
{
  "category": "Arrays",
  "name": "ARRAYSIZE",
  "tests": [
    {
      "name": "Wrong type SYSCALL[System.ExecutionEngine.GetScriptContainer]+ARRAYSIZE",
      "script": "0x682953797374656D2E457865637574696F6E456E67696E652E476574536372697074436F6E7461696E6572C0",
      "message": "0x00"
    }
  ]
}
```

The proposed draft schema is:
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://neo.org/neovm.json",
  "type": "object",
  "title": "NeoVM Tests",
  "required": [
    "category",
    "name",
    "tests"
  ],
  "properties": {
    "category": {
      "$id": "#/properties/category",
      "type": "string",
      "title": "test category (rename to 'suite' name?)",
      "default": "",
      "examples": [
        "Arrays"
      ],
      "pattern": "^(.*)$"
    },
    "name": {
      "$id": "#/properties/name",
      "type": "string",
      "title": "Name for test suite",
      "default": "",
      "examples": [
        "ARRAYSIZE"
      ],
      "pattern": "^(.*)$"
    },
    "tests": {
      "$id": "#/properties/tests",
      "type": "array",
      "title": "Tests for specific suite",
      "items": {
        "$id": "#/properties/tests/items",
        "type": "object",
        "title": "Each test case",
        "required": [
          "name",
          "script",
          "message"
        ],
        "properties": {
          "name": {
            "$id": "#/properties/tests/items/name",
            "type": "string",
            "title": "specific test name (rename to description?)",
            "default": "",
            "examples": [
              "Wrong type SYSCALL[System.ExecutionEngine.GetScriptContainer]+ARRAYSIZE"
            ],
            "pattern": "^(.*)$"
          },
          "script": {
            "$id": "#/properties/tests/items/script",
            "type": "string",
            "title": "specific test script",
            "default": "",
            "examples": [
              "0x682953797374656D2E457865637574696F6E456E67696E652E476574536372697074436F6E7461696E6572C0"
            ],
            "pattern": "^(0x)?([0-9A-F][0-9A-F])*$"
          },
          "message": {
            "$id": "#/properties/tests/items/message",
            "type": "string",
            "title": "specific test message",
            "default": "",
            "examples": [
              "0x00"
            ],
            "pattern": "^(0x)?([0-9A-F][0-9A-F])*$"
          }
        }
      }
    }
  }
}
```

Material on JSON schema may be found here: https://json-schema.org/understanding-json-schema
Validation can be experimented here: https://www.jsonschemavalidator.net

Right now, my only suggestions are to rename "category" to "suite" (or "testsuite"), and "name" to "description" (inside tests). I also suggest the inclusion of a field "version", to evolve this standard in the future. The part of "steps" is still unfinished, it will take a little work, but I think it can be finished very soon.

**Comment by ixje** [comment]
Nice! I had a schema on the TODO once the draft was finalised. 
fyi; I don't know if you're doing this manually, but there are tools which you feed a bunch of JSON files and it will spit out a matching schema. Then you'll only have to fine tune it (mostly on the pattern side)

**Comment by igormcoelho** [comment]
Oh, nice @ixje ! I'm building manually haha but it's fun ;)

**Comment by fyrchik** [comment]
Currently there is a custom behavior for the `TestEngine` which is used in JSON tests when `SYSCALL` followed by 4 `NIP` pushes new `InteropItem` onto stack. This means that some of the test scripts will actually execute differently on "vanilla" VM.
https://github.com/neo-project/neo-vm/blob/a69479838da4d426a901cdd4dd5b861f77fd2575/tests/neo-vm.Tests/Types/TestEngine.cs#L9

There are at least to other ways to do this:
1) modify JSON schema to add possibility to specify initial stack state in tests
2) add new SYSCALL (or opcode NEWINTEROP) to support creating custom interop items on stack

May be we could come up with more. What do you think?

**Comment by ixje** [comment]
Just to clairfy, it's not really 4 `NIP` instructions a 4 byte operand to the `SYSCALL` instruction. That aside, I think option 1 is an interesting extension to make more complex and complete tests in a simpler fashion. Simpler by being able to setup stacks directly instead of having to build it via a sequence of opcodes + data.

**Comment by shargon** [comment]
Votes for option 1 Thumb up, 
Votes for option 2 thumb down

**Comment by igormcoelho** [comment]
Option 1 is the way to go. Let's just "mock" Stack InteropInterface with json.

**Comment by shargon** [comment]
we are all agree in option 1
