### ISSUE TITLE
Create IExecutionEngine

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo-vm#112]
We need to have some sort of interface for ExecutionEngine, in order to better test features inside Neo without needing to have a full system set-up. If we have that interface, we can use mock and test only the desired features when necessary (example, verify if a given Interop actually pushes on stack the expected value).

**Comment by erikzhang** [comment]
I think we need a fully tested NeoVM and then test Neo based on it. There is no need to create an `IExecutionEngine` interface.

**Comment by igormcoelho** [comment]
Ok, agreed, focus on testing first.

**Comment by igormcoelho** [comment]
If necessary, I'll re-open.
