### ISSUE TITLE
Unified Entry Point

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo-vm#122]
Erik, I think it's time to come back to this issue: https://github.com/neo-project/neo-vm/issues/54#issuecomment-426526479

Unified entry point for all verification methods. Together with this, we can abolish CHECKSIG and MULTISIG, for Neo 3.0, and implement them as Native contracts using VERIFY.

**Comment by erikzhang** [comment]
I hope we can abolish `CHECKSIG` and `CHECKMULTISIG`. But the big difficulty is that they are already widely used in user addresses. If we abolish them, the uses have to change their addresses.

**Comment by igormcoelho** [comment]
New Neo, new address :laughing:
just kidding... we can find a way Erik, to make some correspondence before migration. We may create the new option, and start forbidding new addresses before migration... although its nice to have similarity to bitcoin opcodes. Lets think..

**Comment by shargon** [comment]
Unified in neo 3
