### ISSUE TITLE
Will VM ever support GPU?

### ISSUE THREAD

**Issue by rickyhan** [neo-project/neo-vm#14]
It will be immensely powerful if it supports even this most basic GPGPU op codes.

**Comment by erikzhang** [comment]
Is there a specific scenario that you need this for?

**Comment by rickyhan** [comment]
For building AI contracts that require GPU's to accelerate learning. It's nothing more than a thought experiment at this point. It'll be very hard to implement.

**Comment by rickyhan** [comment]
Example contract: https://docs.agrello.org/Agrello-Self-Aware_Whitepaper-English.pdf
