### ISSUE TITLE
Remove SHA's from neo-vm

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo-vm#152]
https://github.com/neo-project/neo-vm/blob/58b7a3aa1fcf1a7c3538451d13e66b1c2c2ad405/src/neo-vm/OpCode.cs#L640-L649

Still remains

**Comment by erikzhang** [comment]
We are going to keep them.

**Comment by vncoelho** [comment]
Let's think about it again, why to remove HASH and leave SHA?
HASH is basically SHA256 twice.
I think that vm will be clear.

**Comment by erikzhang** [comment]
I removed `HASH*` because they can be replaced by combining `SHA*`.

**Comment by vncoelho** [comment]
Exactly, I understood, as I said above.

However, these SHA's are kind of the last non-trivial operation in the neo-vm, @erikzhang.
By moving it to an upper layer we have more flexibility for other unidirectional formulas.

**Comment by diskooooo** [comment]
Perhaps good to take this into account: https://www.zdnet.com/article/sha-1-collision-attacks-are-now-actually-practical-and-a-looming-danger/

**Comment by shargon** [comment]
done
