### ISSUE TITLE
Need calc scripthash in NEOVM

### ISSUE THREAD

**Issue by lightszero** [neo-project/neo-vm#159]
we should add this functions to opcode.

        //Syscall("System.ExecutionEngine.GetEntryScriptHash")
        ENTRYSCRIPT = 0xD0,
        //Syscall("System.ExecutionEngine.GetExecutingScriptHash")]
        CALLINGSCRIPT = 0xD1,
        //[Syscall("System.ExecutionEngine.GetCallingScriptHash")]
        EXECUTINGSCRIPT = 0xD2,

this is base function,like implement static variable.
static variable is shared by same script,so we need to compare executingscript

we can store static vars like this:
map<scripthash, static vars>

so when we use a static var,opcode maybe like:

> DUPFROMSTATICSTACK，//get map
> EXECUTINGSCRIPT,           //get key :scripthash
> PICKITEM                          //get vars=map[key]
> PUSH var id                       //get key:var id
> PICKITEM                          //get var=vars[key]
> 

I think neocompiler use syscall to get executingscript for static variable is a bad idea.  
syscall is more slower than opcode.
and this will make neocompiler to write a fix syscall.

**Comment by lightszero** [comment]
@neo-project/core what do you think?

**Comment by shargon** [comment]
We recently remove it 😆 
Doesn't care the Hash format? maybe we can do a SHA1 of the script?

**Comment by erikzhang** [comment]
Why do we need hash functions in VM? Just like other stacks, share them within the contract and isolate them outside the contract.

**Comment by lightszero** [comment]
We have 3 level

ExecutionEngine > Script > ExecutionContent.

static vars is shared in script level.

a1()->appcall b1()->appcall a2();  

a1 a2 come from same script,so then can shared static vars.

so we need to add a stack for script.

one way is add a stack on Executionengine level,and store like this map<scripthash, static vars>.
another way is fix NEOVM to add a actually script level Stack.

**Comment by igormcoelho** [comment]
lights, what are MSIL opcodes for a static variable?
I prefer another stack on script level thana shared map with "simulated" context.

**Comment by lightszero** [comment]
@igormcoelho  

msil opcode for static variable is  Ldsfld

static vars saved on type  in msil,we do not have type,so we will save static vars on script level.

I think that static vars is no need to be storaged ,no need for across many execution.

and here is a case:

class A
{
    static int count;
    Main()
    {
        count =0;
       for(...)
       {
          A();
       }
    }
    A()
    {
       count++;
       if(count>5)
           return false;
    }
}

**Comment by lightszero** [comment]
no need for a1()->appcall b1()->appcall a2();
so we donot need scripthash.
