### ISSUE TITLE
ByteArray not IsArray = true?

### ISSUE THREAD

**Issue by notatestuser** [neo-project/neo-vm#16]
Why is this not in ByteArray?
https://github.com/neo-project/neo-vm/blob/8c87712c651a6d6af3e4169da8e858e378fe7114/src/neo-vm/Types/Array.cs#L10

The VM is entering a FAULT state when a SETITEM is used on my byte array. See below:

```csharp
case OpCode.SETITEM:
   {
         StackItem newItem = EvaluationStack.Pop();
         if (newItem.IsStruct)
         {
            newItem = (newItem as Types.Struct).Clone();
         }
         int index = (int)EvaluationStack.Pop().GetBigInteger();
         StackItem arrItem = EvaluationStack.Pop();
         if (!arrItem.IsArray)   // <------ the isArray check
         {
            State |= VMState.FAULT;  // <-- :(
            return;
         }
```

**Comment by lightszero** [comment]
On NeoVM，actually，String and Integer and BigInteger had convert to ByteArray.
so ByteArray is a special type for NeoVM，not as a Array Type.
