### ISSUE TITLE
VMState used as a FlagsEnum though it lacks FlagsAttribute

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-vm#188]
It seems like VMState is expected to be used as a flags enum. 
- ExecutionEngine and Debugger do bitwise operations on VMState https://github.com/neo-project/neo-vm/blob/7f93c34ca4336b54764ce815d8504d9d55d38a0e/src/neo-vm/ExecutionEngine.cs#L181
- VMState values are defines as powers of two (0, 1, 2, 4) so they can be used in bitwise operations.
- On the other hand, Debugger does some non-bitwise operations on VMState https://github.com/neo-project/neo-vm/blob/master/src/neo-vm/Debugger.cs#L61-L70

If VMState is supposed to be used as a bit field, it should carry the [FlagsAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.flagsattribute)

**Comment by shargon** [comment]
we should remove all the flag checks, only equal and distinct

**Comment by erikzhang** [comment]
We can currently not use `Flags`, but we should retain the possibility of converting into `Flags` in the future.

**Comment by devhawk** [comment]
If VMState is intended to be used as a flags enum, it should be marked as such. Since it is not marked as flags, code shouldn't be doing bitwise operations on it.
