### ISSUE TITLE
Function pointers

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo-vm#190]
UPDATE: this changed from LambdaStackItem to a FunctionPointer stack item, during progress.

-----

Design: https://github.com/neo-project/neo-vm/issues/190#issuecomment-562585355

----

I think we will need a very nice new stack item type, called LambdaStackItem :)

@erikzhang I've been thinking a lot, and a lot, and I've been convinced that OP_EVAL is not a good idea, due to its insecure and "poor-programming" nature: https://github.com/neo-project/neo/issues/328

However, we have an alternative. We can have a StackItem type that carries a Script, and a specification for inputs/outputs. 

We will require a new opcode: `NEWLAMBDA`, that specifies inputs/outputs, and a Script (read as regular sequence of bytes), read from stack. I think it's important to read from stack (rather than direct parameters), because we can make it much more powerful (not using only compiled code, but also those passed by users on contract).

This is much safer than OP_EVAL. This "Lambda" StackItem will not process recursion, nor any types of CALL (loops are fine, "perhaps"). Perhaps, it's better not to allow SYSCALLS too, although I'm not fully sure of it. Certainly, storage operations are not desirable, but some basic JSON, serialization, deserialization, etc, may be welcome inside a lambda.

Hopefully, this may help us solve this: https://github.com/neo-project/neo/issues/880#issuecomment-513678289

**Comment by igormcoelho** [comment]
@lightszero @shargon what do you think?

P.S.: I still want to abolish one of Array or Struct (probably Struct). I have some new arguments to go back on that discussion.. just wait a little bit more ;)

**Comment by igormcoelho** [comment]
@vncoelho I think lambdas will solve best our problems too.

**Comment by vncoelho** [comment]
I will call you soon for understanding it better, brother.
Trying to hunt that P2P duplicated tasks and invpayloads.

**Comment by igormcoelho** [comment]
Guys, I just saw that, receiving scripts on runtime to add on a LambdaStackItem will cause issues, as we won't be able to pre-calculate the estimated script time (some use could pass different things as parameter, build a lambda, and execute it on verification).
This thing will be far less powerful, but we can hardcode on it its script and input/outputs. It's much safer too, and still allows us to build and re-use lambdas on code (generated by on compile-time).

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo/issues/284

**Comment by erikzhang** [comment]
Maybe `FunctionPointer`?

**Comment by vncoelho** [comment]
@erikzhang, it also sounds good, could we point to a deterministic function of the SC that access storage?

**Comment by erikzhang** [comment]
In VM, we only have the function pointers, which could be used in current contract only.

We can add a new SYSCALL `System.Runtime.CreateCallback` in NeoContract, which accepts the pointer, and creates a wrapper of the pointer. We name it as a `Callback`.

The contract can pass the callback to other contracts. So callbacks can be used across contracts.

**Comment by vncoelho** [comment]
This is quite powerful, @erikzhang. Let's discuss with @igormcoelho to check if it will be enough to cover the cases he thought.

**Comment by erikzhang** [comment]
One thing should be kept in mind. If `A` calls to `B` and sends a callback to `B`, and `B` calls the callback.

```
A -> B -> A(callback)
```

Can the callback function access `A`'s static fields?

**Comment by erikzhang** [comment]
```c#
class A : SmartContract
{
    private static int MyInt;
    private static void TestMethod()
    {
        //What is the value of `MyInt`?
    }
    public static void Main()
    {
        MyInt = 2;
        Callback callback = CreateCallback(TestMethod);
        B.Main(callback);
    }
}
class B : SmartContract
{
    public static void Main(Callback callback)
    {
        callback();
    }
}
```

**Comment by igormcoelho** [comment]
Interesting Erik, my only concern is this (regarding callback):
PUSH1
PUSH2
ADD
Runtime.CreateCallback

Could we do this? If we can, this breaks all optimizations...  if we could use direct parameters on this, ok, at least it's not a relative jump, but like this it's a relative jump, and we should not have that. Do you think direct parameters is feasible at least on this case?

**Comment by erikzhang** [comment]
> Could we do this? If we can, this breaks all optimizations...

Of course not. `CreateCallback` accept the function pointer only.

**Comment by igormcoelho** [comment]
But how do you know an specific point is a function? Perhaps I'm missing something... I know it's easy to do on C# compiler, but my problem is with other possibilities manually done, where an offset may not necessarily correspond to a function entry point.

**Comment by erikzhang** [comment]
`PUSHPOINTER` accepts address only. It doesn't pop the stack.

**Comment by igormcoelho** [comment]
I see Erik, if it works, that's fine for me.
If it works like this: `SYSCALL "System.Runtime.CreateCallback Func1` it would be simpler I guess.

**Comment by igormcoelho** [comment]
I'm a bit confused, I'll try to think better on it.

**Comment by erikzhang** [comment]
`PUSHPOINTER` is necessary. Because it is lightweight, it can be used inside the contract.

And SYSCALLs accept parameters from stack only.

**Comment by vncoelho** [comment]
Func1 is set on SC, direct parameter, yes? Or dynamic from stack?

**Comment by igormcoelho** [comment]
> SYSCALLs accept parameters from stack only

Ok, I'll assume this.

> PUSHPOINTER is necessary

If we cannot have direct parameters on interop, we must find another way to do it... one way is to do it by a PUSHPOINTER opcode, that only accept direct parameter.

I think I get that, it must solve the problem :+1:

**Comment by shargon** [comment]
> Can the callback function access A's static fields?

In c# yes, so my vote is yes... always will be danger if you send a callback to other contract, if you have you Storage Context static... you will be dead, but in other languages it works like this

**Comment by erikzhang** [comment]
We need two new opcodes:

```c#
enum OpCode : byte
{
    PUSHA, //Push the address of a function onto the stack.
    CALLA, //Pop an address from the stack, and call the function.
}
```

**Comment by igormcoelho** [comment]
oh! very interesting point Erik, I was just going to mention that  would be strange having only PUSH without any consumption method on neo-vm, for function pointers. Now it's fine. Agree with PUSHA and CALLA.
Do you think it's nice to use it for general calls now Erik? Or only for callback situations? I mean, is there any semantic advantage of doing:
`PUSHA address`
`CALLA`

instead of: 

`CALL address` ?

**Comment by erikzhang** [comment]
Two instructions vs one instruction.

**Comment by igormcoelho** [comment]
> Two instructions vs one instruction.

Ok, now I get it. So CALL would be an optimization, precisely: CALL X = (PUSHA X, CALLA)
For me that's good enough.

**Comment by shargon** [comment]
Change address by offset?

**Comment by igormcoelho** [comment]
> Change address by offset?

You mean, instead of absolute (to the start of NVM), put relative to the current position of executing code (like a jump)?  Both work for me I guess, it should be just arithmetics.

--- 

Now, regarding security and static data access. 
> Can the callback function access A's static fields?

Conceptually, a callback should be able to do that. When user provides a function to be executed by the contract, contract wont't be able to know in advance its contents. In the situation you mentioned, user will be able to mess with any existing static field on the contract, so I would recommend disabling it.

Other possibility, which is more related to the concept of lambda itself, is the ability to load static NVM script on a stack object "FunctionPointer", like that:
LOADSCRIPT 0102... NVM script
And invoke it via CALLA.

Naturally, CALLA would execute this code in a shielded context, since it's an independent code, so it wouldn't access/change static data. In fact, it wouldn't interfere with any contract state, only process and return value.

This is different from callback (which is part of the contract itself), and different from OP_EVAL (with unpredictable stack code execution).

So, callbacks themselves could access static fields, while lambda objects could not, and user chooses what it wants (by simply verifying if FunctionPointer has code or offset data,  perhaps by another opcode ISSCRIPT over FunctionPointer).

**Comment by igormcoelho** [comment]
If we want to simplify, we just disable static access on CALLA FunctionPointer, and it would be safe enough for the user to provide and create its own "lambda" on Entry (so just PUSHA and CALLA would suffice).

**Comment by vncoelho** [comment]
@erikzhang, I just saw that the title was changed.

This is not yet the functionality we were needing with lambda. Are you still considering a design for lambda calls?

**Comment by erikzhang** [comment]
I don't know what's the difference?

**Comment by shargon** [comment]
> You mean, instead of absolute (to the start of NVM), put relative to the current position of executing code (like a jump)? Both work for me I guess, it should be just arithmetics.

No, offset from the beginning 0, it's an address but for prevent to have two different concept for "address" i think that we can call it offset.

**Comment by erikzhang** [comment]
@shargon It's not an offset. It is an absolute address.

**Comment by vncoelho** [comment]
@erikzhang,

>I don't know what's the difference?

 Lambda would allow us to cache a function on the stack (opcodes representing a desired function) coming from parameters of an Invoke.

First execution: define function
Main(byte[] script, byte[] param)
LOAD script - loads in the stack of pointers
LAMBDA script with param - use the pointers to call the script with param as parameters

This is different than opeval, which would dynamically load.

**Comment by erikzhang** [comment]
Does it accept script from stack? Can it be passed to another contract?

**Comment by vncoelho** [comment]
Not from the stack, just temporary from parameters.

It can be called as a normal callback with desired params.

**Comment by erikzhang** [comment]
Then they are equivalent and can be converted to each other.

**Comment by erikzhang** [comment]
```
LOADSCRIPT <some script>
CALLA
```

```
PUSHA L1
CALLA
RET
L1:
//some script
RET
```

They are equivalent.

**Comment by vncoelho** [comment]
How to have a dynamic function on a predefined Smart Contract?

The case is when someone wants to Evaluate something with a dynamic function that comes from an invocation (older or send at the same time that caller wants to evalute).

Is this possible with the current solution?

**Comment by vncoelho** [comment]
In your example, @erikzhang , can L1 behave dynamically? We would need to setup it.

**Comment by erikzhang** [comment]
I don't know what do you mean.

**Comment by igormcoelho** [comment]
> They are equivalent.

I agree Erik, in this case yes... our initial goal was to be able to inspect the lambda code, and take a hash of it (to guarantee that user has passed correct script). Taking content of a NVM function is not possible, since we don't know where it ends... 
But in the end, I think we can implement it using Witness @vncoelho ... we force user to send specific witness, with specific hash, for every operation we want to verify... at least it will work for us.

**Comment by erikzhang** [comment]
If you don't allow the script from stack, and not allow to pass the pointer to another contract, they are equivalent.

**Comment by vncoelho** [comment]
L1 looks like to be a pointer to a deployed function that can not be modified, static function behavior in terms of logic.

**Comment by igormcoelho** [comment]
It's just the capability to inspect the Lambda content (or at least the hash of it), that's the small difference for us. 
`LOADSCRIPT <some script>`
`INSPECTSCRIPT -> pushes script to stack, this was the original intention`
`CALLA`

what we wanted:

Entry:
User implements some function, and loads it via PUSHA, sending to our contract.

Our contract gets the "function" (now just a function pointer), verify that it matches our "format", and allows its execution or not. Right now, we won't be able to do that using callbacks, because we won't be able to inspect its code (even for reading).

But Witness verification script can solve it, but much harder, and only for boolean results:

Entry:
User invokes our contract informing the script.

Contract verifies witness list, against the hash of the passed script. If they match, we allow execution of the contract. Limitations will be that no storage access, or result different than bool will be allowed. But we can manage @vncoelho

**Comment by vncoelho** [comment]
@erikzhang, it is ok, let's use the witness system for that.

**Comment by igormcoelho** [comment]
Oh, merged? nice!!

**Comment by shargon** [comment]
> But the correct Lamda or OpEval would be the more correct and efficient way.

I don't like OpEval 😅

**Comment by vncoelho** [comment]
You are using it on all NEO invocations with Witness, perhaps you like.

**Comment by igormcoelho** [comment]
Congratulations @erikzhang at least now we have a good design to make filters operational 💪
