### ISSUE TITLE
A proposal for try-catch

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo-vm#192]
I think we can do something like:

TRY 0010

This new opcode TRY will store on.current ExecutionContext where to go if some exception happens (like regular branches). 

THROW and THROWIFNOT will accept a hardcoded
string parameter to inform exception identifier, which is returned to context to treat exception.

Every context can have these things, to allow method call inside try-catch, but you cannot nest one try-catch inside other (dont know if c# allows it too).

Example

int y = 0;
try {
int x = 10 / y;
}catch(Exception e)
{
Runtime.Notify(e.message());
}

this would generate NVM

push0
try 0008
push10
div
jmp AFTER CATCH
.# this is address 0008
CATCH (another opcode to push exception reason??)
syscall Runtime.Notify 

This would print "DivideByZeroException" (added on DIV opcode fault reason).

we can also.not need CATCH if we simply push exceptuon reason to stack begore moving to catch block.

Another option for CATCH is to replace the JMP, and cleanup TRY settings... 
it would be CATCH 0012 (address after catch)

**Comment by igormcoelho** [comment]
Good luck @lightzero :joy:

**Comment by igormcoelho** [comment]
Detailed designed (on computer now):

```cs
int y = 0;
try {
int x = 10 / y;
}
catch(Exception e)
{
Runtime.Notify(e.message());
}
return;
```

```
0000: PUSH0
0001: TRY 0006
0004: PUSH10
0005: DIV
0006: CATCH 000X
0009: SYSCALL Runtime.Notify
000X: RET
```

**Comment by erikzhang** [comment]
It's not a good design. 😂

**Comment by igormcoelho** [comment]
It's good Erik, trust me :joy: 
I thought about it, and it I think.it works for MSIL, specially the last proposal.
what msil does is treating try catch as branches, very similar to what I'm proposing. But only when I see a feasible conversion, I'll be 100% sure too.

**Comment by shargon** [comment]
Something like `TRY (offsetGoodResult) +(offsetBadResult)`

On the opcode TRY, we create a new `ExecutionContext`, and acording to the result, JMP to good or wrong offset (and reset the state to BREAK)

**Comment by igormcoelho** [comment]
I introduced catch opcode to free internal context info of the expecting try... but finally is easier: on the end of block try we JMP to finally (skipping catch), and in the end of catch we also JMP to finally. If there's no.finally, CATCH will jump to next line ;)

**Comment by fyrchik** [comment]
> THROW and THROWIFNOT will accept a hardcoded
> string parameter to inform exception identifier, which is returned to context to treat exception.

What do you think about accepting a byte parameter?
There are 2 advantages:
1. Smaller script size.
2. Clearly defined and documented list of possible exceptions.

**Comment by igormcoelho** [comment]
The only issue I see @fychik is limiting to 256 exceptions... but since Smart Contracts are usually small, it should be able to handle it. The other point is that a Stack Item should be perhaps carried together with the exception, so an informative return can be presented and processed.

**Comment by lightszero** [comment]
I agree this design.
But I think use BeginTry   EndTry as name will be better.
0000: PUSH0
0001: BeginTry 0006 //Begin try block and set the catch function entrypoint.
0004:     PUSH10
0005:     DIV
0006: EndTry 000X //End the try block and jmp to 000x
0009:     SYSCALL Runtime.Notify
000X: RET

**Comment by shargon** [comment]
Do we need Try/catch in SC?

**Comment by lock9** [comment]
Hi @shargon, I think it is needed. I have to say that deterministic code shouldn't need this, because you can determine the results prior to sending it to the network, however, I think this is needed so we can treat the exceptions or get error messages. This will potentially help developers a lot and also make the contract closer to real-life applications.

**Comment by shargon** [comment]
But maybe changing some syscalls we can ovoid the try/catch necessity

**Comment by lock9** [comment]
@shargon  I think it is impossible to remove the try-catch. How are you going to continue execution when the VM state becomes FAULT? We need a mechanism to allow it go to fault and return to running state (if the fault is accepted by the code)

**Comment by lock9** [comment]
In overview, what we need it:
1. Create BeginTry OpCode
2. Create EndTry OpCode
3. Add new VM State to when inside "Try"
4. Add "Try Depth" to support "inner try" (we should FAULT only if try depth is "0" and an exception occurs)
5. Create a new custom Exception class 
6. Push error message and possibly error code into stack when exception occurs
7. Save/Recreate execution context 

@neo-project/core  am I missing anything?

**Comment by shargon** [comment]
and finally how will be implemented, a JMP?

**Comment by erikzhang** [comment]
I think we don't need a `Try` state. But we need a `TryStack`.

**Comment by lightszero** [comment]
let's foucs on changes about opcodes and devpack
like:
1.create BeginTry
2.create EndTry
need finally or not
multiple catch or not
throw what?


3 4 5 6 7 is about implement,we can disuss that later.
fix execution context is enough.
3.no need try state,when fault ,let execution context to deside stop vm or continue with catch.
and execution context can ask parent.
4.no need try depth
I think eric's tryStack is for this. 
5.yes,but opcode throw do not have param fornow,we need change it.

**Comment by erikzhang** [comment]
To design a complete exception handling system, we need at least the following opcodes:

```c#
enum OpCode : byte
{
    THROW = 0x37,
    THROWIF = 0x38,
    THROWIFNOT = 0x39,
    //Reserved 0x3A
    TRY = 0x3B,
    TRY_L = 0x3C,
    ENDT = 0x3D, //End try
    ENDC = 0x3E, //End catch
    ENDF = 0x3F, //End finally
}
```

**Comment by lock9** [comment]
Hi,
What is the difference between TRY and TRYL?
Also, if these are variable names, maybe we could use the complete name, like "ENDTRY" and "ENDFINALLY".

**Comment by igormcoelho** [comment]
TRYL should address bigger steps for jump, probably 4 bytes, while regular TRY would use 2 bytes only.

**Comment by lightszero** [comment]
Hi everyone @neo-project/core
how about this?
throw can throw anything like a string a bytearray.  
and do not use a exception object.

```c#
try
{

}
catch //no (Exception),do not use Exception for contract.
{
}
```

```
THROW(no data) 1 stack value: var a = stack.pop();  throw a;
THROWIF(no data)2 stack values:  var a= stack.pop();var b=stack.pop(); if(b)throw a;
THROWIFNOT(no data):  same with THROWIF
TRY(u16:catchbegin_ptr,u16 finalbegin_ptr) no stack value
TRY_L(u32:catchbegin_ptr,u32 finalbegin_ptr) no stack value
ENDTRY(no data)no stack value
ENDCATCH(no data)no stack value
ENDFINALLY(no data)no stack value
```

we need to confirm this soon.

**Comment by shargon** [comment]
> `catch //no (Exception),do not use Exception for contract.`

What this means, it will support different kind of exceptions or not?

```
try{}
catch(FormatException ex){ } 
catch(ArgumentNullException ex){ } 
```

**Comment by lightszero** [comment]
@shargon I think do not support Exception  for now is better.
or else we must add Exception object support.
we support this fornow
```c#
try{}
catch{ }
```

and support this in future
```c#
try{}
catch(FormatException ex){ } 
```

**Comment by Tommo-L** [comment]
Could I remove the `throwif`, `throwifnot`? I think `throw` is enough.

**Comment by erikzhang** [comment]
`THROWIFNOT` is useful in bulk transfers.

```
APPCALL <hash> ["transfer", [<address>, <address>, <amount>]]
THROWIFNOT
APPCALL <hash> ["transfer", [<address>, <address>, <amount>]]
THROWIFNOT
...
```

**Comment by Tommo-L** [comment]
We should decide which should throw `InvalidProgramException` -- @shargon 
And try-catch-finally will handle which types of exception?

**Comment by shargon** [comment]
I think that we only should be able to catch if this return false

https://github.com/neo-project/neo-vm/pull/294/files#diff-76ae2659301a783b97ae4c99999464ccR1347

Otherwise it could produce non deterministic results in different languages. 

And we should try to change some logic for return false. For example 

```
case OpCode.CONVERT:
                    {
                        if (!TryPop(out StackItem x)) return false;
                        Push(x.ConvertTo((StackItemType)instruction.TokenU8));
                        break;
                    }
```
To
```
case OpCode.CONVERT:
                    {
                        if (!TryPop(out StackItem x)) return false;
                        if(!x.TryConvertTo((StackItemType)instruction.TokenU8, out var item)) return false;
                        Push(item);
                        break;
                    }
```

**Comment by Tommo-L** [comment]
> I think that we only should be able to catch if this return false

Agree.

But `return false` isn't clear, I prefer to use throw *Exception in those false cluases, like change `TryPop` to `Pop` with exceptions.

**Comment by shargon** [comment]
yes, i was thinking about and maybe we should be more specific about when we should allow the try/catch.

what happens in something like that

```
TRY
POP<- ERROR
POP
CATCH
```

The stack will be unusable, because it expected to remove 2 items, and only removed one. We must know when it's valid to catch the exception, and when not.

**Comment by shargon** [comment]
we can return a enum, Good, Error or CatcheableError, instead of a bool?

**Comment by Tommo-L** [comment]
If the following case happens, what do we do with the `EvaluationStack`? Empty, keep, or roll back to the try?
```
push 
try
   push 
   push
   push
   pop 
   pop  <- error
   pop 
   ...
endtry
...
```
Therefore, I still think the `try-catch` only handle the error throwed by `throw/throwif/throwifnot`, it will simplify the processing logic. 
And also, if there a lot of errors throwed by vm itself to be catched, it will increase uncertainty between multilingual versions.

**Comment by Tommo-L** [comment]
I recommend handling exceptions thrown by the `throw*` instruction for now, and thinking about extensions later.

**Comment by shargon** [comment]
I think that we should have a whitelist of the instructions availables for catch. For the begining we can allow only `throw` and `convert`

**Comment by Tommo-L** [comment]
Okay

And what do you think we should do with the `EvaluationStack` when `convert` failed.

**Comment by shargon** [comment]
> And what do you think we should do with the EvaluationStack when convert failed？

If the error was in the point 1, the error should not be able to be "catched", it's a compilation error.
If the error was in the point 2, it's possible to be "catched", because the stack remains usuable.

![image](https://user-images.githubusercontent.com/3167973/75091617-97849200-556f-11ea-9c7d-d544c0a445b9.png)

**Comment by Tommo-L** [comment]
In case two, the stack may also be unusable. We can't guarantee that there will be no other `trypop` operations after `convert`.

**Comment by lightszero** [comment]
We have slot now,so compilers just use  EvaluationStack  for  smallest calc operation.
push
push
add
stloc ;// because we use lots of stloc and ldloc

so just tell compiler to use stloc more

**Comment by Tommo-L** [comment]
> so just tell compiler to use stloc more

I think It still has the above problem.

**Comment by Tommo-L** [comment]
In the future, we can consider adding this `throw` format.
![image](https://user-images.githubusercontent.com/43396869/76286276-a2b01f80-62dc-11ea-8e3b-9b3eff20d22e.png)
(example from belane's nep5 template）

**Comment by shargon** [comment]
> In the future, we can consider adding this throw format.

We must do it
