### ISSUE TITLE
EQUAL returns False when applied to 2 empty arrays

### ISSUE THREAD

**Issue by fyrchik** [neo-project/neo-vm#201]
I'm currently looking into NeoVM json tests and noticed some unexpected behavior.
When applied to 2 empty arrays EQUAL returns false
https://github.com/neo-project/neo-vm/blob/332db08ada15916e69451fc9a23075574ac511a1/tests/neo-vm.Tests/Tests/OpCodes/BitwiseLogic/EQUAL.json#L477

`ArrayItem.Equals` uses `ReferenceEqual` to check on equality (introduced in this commit:
https://github.com/neo-project/neo-vm/commit/80ea35d741eae45f1293a0f9bd6e494cab1a59cf )

Is it the expected behavior? What is the logic behind this decision?

**Comment by erikzhang** [comment]
Yes. It is the expected behavior. Arrays are reference types in NeoVM.

You can find similar behavior in JavaScript:

```html
<script type="text/javascript">
    var x = [];
    var y = [];
    alert(x == y); //false
</script>
```
