### ISSUE TITLE
add 3.0 preview tag

### ISSUE THREAD

**Issue by ixje** [neo-project/neo-vm#203]
Can we get a `v3.0.0-preview` tag like the `neo-cli` and `neo` projects? This will ease checkout and creating a v3.0 preview setup.

**Comment by shargon** [comment]
Agree

**Comment by ixje** [comment]
bump

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo-vm/releases/tag/v3.0.0-preview1

Done.

**Comment by ixje** [comment]
thanks!
