### ISSUE TITLE
reorder opcodes on nvm3

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo-vm#212]
As discussed on https://github.com/neo-project/neo-vm/pull/208, it could be a good idea to reorganize opcodes on nvm3.
One thing I would propose is to move PushX opcodes to the beggining, so 05 would be number 5, and so on... this could be connected to a low-level serialization standard.

**Comment by erikzhang** [comment]
`0x05` is `PUSHBYTES5`. So `0x051234567890` is to push `0x1234567890` onto the stack, and `0x05` will be the length prefix.

I don't think moving them is a good idea.

**Comment by igormcoelho** [comment]
PUSHBYTESX pattern is not very efficient Erik, I'll explain why.

Currently, we can use PUSHBYTES from 0 to 75 (opcodes 0x00-0x4b), an inheritance from Bitcoin VM (https://en.bitcoin.it/wiki/Script), also the following opcodes PUSHDATA1, 2 and 4 (that goes up to 4GiB). Regarding numbers, we can PUSH 1 to 16 (opcodes 0x51-0x60), another inheritance from Bitcoin. On total, 96 opcodes are dedicated to this.

Yet, if we want to push number 17, which is a small number, this would require two ops: PUSHBYTES1 + 17, and this happens to all small numbers after 16. I am constructing a serialization standard for Neo for a while, inspired on real "Neo" stuff, and I believe the VarBytes pattern on Neo is more efficient than any of these (inherited from Bitcoin).

I propose a simplification that would be very likely more efficient than any of these.

Proposed table:
- Opcodes 0-127 (`0x00-0x7f`): PUSH NUMBER X. So, we would start with PUSHX (push numbers) instead of PUSHBYTES.
- Opcode 128 (0x80) : PUSH NUMBER -1. This is good for two reasons: we provide direct access to numbers/symbols up to half-byte; and -1 is already serialized as 0x80.
- Opcode 130 (0x82) : PUSHVARBYTES. This opcode would replace all existing PUSHBYTES, in currently existing pattern: first byte indicates size, up to 253 (small - 2B), then 254 (medium - 3B), then 255 (huge - 4B). This simplifies development a lot. Regarding drawbacks, if we want to push a string with 5 bytes (PUSHBYTES5), now we would need one extra byte: PUSHVARBYTES + 5 + 5 bytes. One bad situation would be to push a tiny number such as 255... one would need: PUSHVARBYTES + 1 + 0xff (3 bytes to push a one byte value). For this reason, I propose the next opcode (intentionally out of order here).
- Opcode 129 (0x81) : PUSHBYTE. Now, if we want to push 255, we do: PUSHBYTE + 0xff (two bytes for one byte). But note that, on NeoVM2 we also needed this after value 75... to push byte 76, we would need PUSHBYTES1 + 76, and I don't think there's a good reason to swap logic after 75, but there's a good reason to swap logic after 127, as proposed here (one good example is BigInteger serialization).
- Opcodes 131 - 255. What else? Now we need to fit all the rest of opcodes in 124 slots. I did a rough calculation, and we can do that, and in an even better organized format.

**Comment by igormcoelho** [comment]
@erikzhang @shargon @lightszero please consider the above proposal.

**Comment by lightszero** [comment]
in my view.
we have too mush PUSHs

I think keep 4 is enough.

pushbytes1
pushbytes2
pushbytes4
pushdata [with dynamic data length]

**Comment by igormcoelho** [comment]
> And in my view.
> we have too mush PUSHs

@lightszero precisely that.

My proposal is to focus on: pushbyte, pushbytes2, 4, 8, 20, 32, 33, 64. The rest can be varbytes.

**Comment by shargon** [comment]
>I think keep 4 is enough.
>pushbytes1
>pushbytes2
>pushbytes4
>pushdata [with dynamic data length]

pushbytes20, 16 and 32 are useful for hashes

**Comment by shargon** [comment]
But take in mind that this opcodes never reduce the performance. Maybe with push bytes64, is enough.

**Comment by igormcoelho** [comment]
I didnt understand your last point Shargon... you mean we only need pushbytes64, and the rest can be varbytes? The difference indeed is just one extra byte for size,but if we know we will use,its good to have. E,g, 0x21 is currently pushbytes33... if we dont have that, we will use a lot: pushvarbyte + 33 + key (one byte extra,but it works).

**Comment by igormcoelho** [comment]
@shargon @lightszero @erikzhang please help me update this comparison table, to compare approaches:

LEGEND:
NeoVM Ops: current implementation of test
NeoVM+ Ops: new implementation of test
Optimal Size: estimated minimum size in bytes for the task (minimum is 1)
Overhead and Overhead+: extra percentual of bytes spent for the task, regarding Optimal Size

|     Test      | Optimal Size | NeoVM Ops | Overhead (%) | NeoVM+ Ops  |  Overhead+ (%) |  
|--------------|-----------------|-----------------|--------------------|-------------------|----------------------|
| push empty bytearray    | 1 | PUSH0  | 0%  |  PUSH0  | 0% |
| push scripthash             | 20 | PUSHBYTES20 + scripthash  |  ~0% | PUSHBYTES20 + scripthash  | ~0% |
| push 76 bytes             | 76 | PUSHDATA1 + 76 + 76bytes  |  2/76% | PUSHVARBYTES + 76 + 76bytes  | 2/76% |

**Comment by shargon** [comment]
`PUSHDATAX` to `PUSHVARBYTES` is a very good move.

**Comment by igormcoelho** [comment]
> PUSHDATAX to PUSHVARBYTES is a very good move.

It's less efficient, but much more standard regarding current Neo serialization model.  I think this counts a lot, to have a strong identity... better than being perfectly efficient, I prefer being simple to understand and easily attract more devs/adopters.

**Comment by shargon** [comment]
Agree, one opcode for dynamic size is enough following the neo standard

**Comment by roman-khimov** [comment]
1. I'd prefer keeping compatibility as much as possible, just changing opcodes (like it was done in #208) doesn't look right to me, these are just numbers that almost no one really cares about. I mean, yeah, all three people implementing NEO VM do care, but other than that, sorry, but no.
2. If we're to change anything here, than yes, it's better to make something more than just moving opcodes around, which leads me to the next point...
3. Has anyone tried to analyze currently used verification/application scripts in Testnet and Mainnet? I mean we have quite a lot of real-world scripts there and they probably can answer a lot of questions. It shouldn't be hard to get real statistics for opcode usage, it should also be possible to try to find some common patterns that can be optimized. Of course all of you have a lot of experience with this VM and you kinda 'feel' what is the right opcode set for it, but still using some real data (that we have!) can only help.

**Comment by igormcoelho** [comment]
@roman-khimov that's precisely the point! If you look at the table up there, it's not just reordering, it's a total rewrite of neo-vm push system. It's completely different, focusing on performance and lessons learned from neo-vm. Just to highlight: that table is just for PUSH.
I did some studies already, and the critical part, in my opinion, is having more direct DUPs and SWAPs. But to keep discussions easier, I was focusing on PUSH first (which is much easier), then moving to the rest, afterwards.

**Comment by roman-khimov** [comment]
> it's a total rewrite of neo-vm push system.

Yeah, I do see it and, to be fair, I do like it. It's just that I'm not sure we're properly taking into account the data that we have in Mainnet/Testnet, real scripts and contracts that we have. You obviously have way more experience with this VM than I do and most probably your suggestions are correct, but for me it would be very interesting to check these suggestions against real data to either prove them or improve them.

For example, PUSHX (0-127) --- do we really need that many of them? What are the most commonly pushed values? I don't know. But checking against real-world scripts can help here. And if we have a VM design very close to Bitcoin's one then we can also consider some data from it.

**Comment by igormcoelho** [comment]
@roman-khimov this proposal has two big aspects involved: (1) simplicity (2) efficiency.
- The PUSHX 0-127 pattern is not meant entirely for efficiency, but mainly for simplicity. The idea is to have a nvm much closer to Neo serialization format, where 05 means number 05, etc. The first attempt was to make a compatible serialization format, while not wasting all available opcodes. From an efficiency perspective, few people may indeed use PUSH67, perhaps almost never, but its implementation costs the same as any other opcode, and doesnt bring any overhead to the machine, since 0 to 127 will implemented as a subtraction, as it is now. In this sense, the overhead of supporting PUSH0-16 and PUSH0-127 is exactly the same, so if we don't improve anything, we won't make it worse, but we will surely make it simpler.
- Number 128 always confused people, because Neo has bigint support, so it's a good strategy to make people use its bigint version (PUSHBYTES2 8000). It's also not less efficient than current opcodes, as 128-256 is also currently pushed in same manner.
- PUSHVARBYTES is a major simplification over PUSHDATA1, 2 and 4, and it makes us so much closer to Neo serialization standard, adopting the same implementation everywhere (good for global understanding of the platform).

That being said, I'm not against analyzing the whole chain to watch pros and cons of this proposal, and I don't think it will be measurable in any performance metric, as the biggest gain of 50% happens on push numbers 17-127, which are not very common I guess. Other changes, like multiple DUPS, will impact more deeply the smart contracts, but we would need to rewrite them to test, and since executions are also very rare in a blockchain, it won't directly affect time. Integrating it on nvm-optimizer is the best shot to demonstrate that we can reduce smart contracts by 70% for example, will something like this convice people perhaps? 
From simplicity perspective, this proposal helps, I think it should be considered. We need a standard Neo3, that fits easily an specification model, and I think this proposal helps a lot in this sense.

**Comment by erikzhang** [comment]
Please review #235.
