### ISSUE TITLE
NULL Opcode compatibility

### ISSUE THREAD

**Issue by shargon** [neo-project/neo-vm#215]
Currently with the last changes of NEO-VM, the null's checks doesn't work as expected and the compiler need to be updated according to this changes

The following code

![image](https://user-images.githubusercontent.com/3167973/67146798-e4d5b780-f28e-11e9-8260-d184dc416dec.png)

 Is compiled as (ILCode)

![image](https://user-images.githubusercontent.com/3167973/67146795-dedfd680-f28e-11e9-9ad9-457ef9e8c6a8.png)

But the Ceq opcode is compiled as

![image](https://user-images.githubusercontent.com/3167973/67146819-059e0d00-f28f-11e9-9f13-2f7cfa4bb449.png)

So I think that the VM need to be updated in order to accept ' null' too in NUMEQUAL

Fixes: https://github.com/neo-project/neo-devpack-dotnet/pull/115 https://github.com/neo-project/neo-vm/pull/214

**Comment by erikzhang** [comment]
@lightszero Can you check it?

**Comment by shargon** [comment]
@lightszero you have the unit test and changes for it here https://github.com/neo-project/neo-devpack-dotnet/pull/115 , Please review it :)

**Comment by lightszero** [comment]
add some fix in  neo-project/neo-devpack-dotnet#115 ,
