### ISSUE TITLE
Refactor Unsafe class in order to use it as public extension

### ISSUE THREAD

**Issue by shargon** [neo-project/neo-vm#227]
We could reuse the `Unsafe` logic in neo, because I think that we can start using `Span` in UIntXXX classes. 

https://github.com/neo-project/neo-vm/blob/c3f58ddc59bd02a1bc8eb3ed3af9893f3576a137/src/neo-vm/Unsafe.cs#L9

**Comment by devhawk** [comment]
can we use https://www.nuget.org/packages/System.Runtime.CompilerServices.Unsafe/ instead?

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo-vm/blob/c3f58ddc59bd02a1bc8eb3ed3af9893f3576a137/src/neo-vm/Unsafe.cs#L9

@devhawk It seems that `System.Runtime.CompilerServices.Unsafe` lacks the methods we need. Such as `MemoryEquals()` and `NotZero()`.

**Comment by erikzhang** [comment]
@shargon NeoVM is not a library that provides utilities. If we need to reuse `Unsafe` logic, we can just copy the code.
