### ISSUE TITLE
Redesign splice opcodes

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo-vm#238]
```c#
public enum OpCode : byte
{
    NEWBUFFER = 0x88,
    MEMCPY = 0x89,
    SETBYTE = 0x8A,
    CAT = 0x8B,
    SUBSTR = 0x8C,
    LEFT = 0x8D,
    RIGHT = 0x8E,
}
```

**Comment by shargon** [comment]
`NEWBUFFER` is like `PUSHBYTESX` ?

**Comment by erikzhang** [comment]
> NEWBUFFER is like PUSHBYTESX ?

No. It is like `NEWARRAY` but creating `ByteArray`.

**Comment by roman-khimov** [comment]
I don't see `SIZE` there, have you decided to drop it? And what's `MEMCPY` gonna look like, what are the instruction parameters and what will it do on the stack?

**Comment by erikzhang** [comment]
`SIZE` is replaced by `ARRAYSIZE`.

`MEMCPY` looks like:

```
MEMCPY(src, srcIndex, dst, dstIndex, count)
```

It clones the `dst` as a new `ByteArray`, and copies `count` bytes from `src` to it.

Why create a new `ByteArray`? Because `ByteArray` in NeoVM is immutable.

**Comment by roman-khimov** [comment]
Just to clarify, it takes all of its five parameters from the stack and then pushes a new `ByteArray` to the stack, correct? What are the length requirements for `dst`, will it expand it if needed or stay within its boundaries?

**Comment by igormcoelho** [comment]
I vote for extension (if on last slot), not memory error,since this will be able to.handle it gracefully (not that low level).

**Comment by erikzhang** [comment]
> it takes all of its five parameters from the stack and then pushes a new ByteArray to the stack, correct?

Yes.

> What are the length requirements for dst, will it expand it if needed or stay within its boundaries?

Since a new `ByteArray` is created, the length will be expanded to `max(dst.Length, dstIndex + count)`.
