### ISSUE TITLE
Redesign bitwise opcodes

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo-vm#239]
```c#
public enum OpCode : byte
{
    INVERT = 0x90,
    AND = 0x91,
    OR = 0x92,
    XOR = 0x93,
    //Reserved 0x94
    //Reserved 0x95
    //Reserved 0x96
    EQUAL = 0x97,
    NOTEQUAL = 0x98,
}
```

**Comment by igormcoelho** [comment]
ISNULL should be on coumpound I guess.

SHIFTL and SHIFTR are gone?

**Comment by erikzhang** [comment]
`ISNULL` can be used for any type, not just coumpound.
SHL and SHR are in #240.

**Comment by igormcoelho** [comment]
Correct, ISNULL accepts any type. Should we support any other type check (isnumber, is bytearray,..)? Perhaps ISTYPE 0 (is null), ISTYPE 1 (is number) etc.
it could be very useful for type matching over an Object return.... it helps a lot operationalize inheritance and "Any" type.

**Comment by erikzhang** [comment]
OK. I will add it.
