### ISSUE TITLE
Improvements on tests JSON files

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo-vm#244]
Currently we are using script in the JSON files directly. But when we change the opcode values, the tests become unavailable.

**Comment by shargon** [comment]
We can add a parser for strings like this:

```
PUSH 0x00
POP
RET
```

**Comment by roman-khimov** [comment]
We write some tests like this in `neo-go`:
```go
func callNTimes(n uint16) []byte {
        return makeProgram(
                opcode.PUSHBYTES2, opcode.Opcode(n), opcode.Opcode(n>>8), // little-endian                                                                                                                                                                                                                             
                opcode.TOALTSTACK, opcode.DUPFROMALTSTACK,
                opcode.JMPIF, 0x4, 0, opcode.RET,
                opcode.FROMALTSTACK, opcode.DEC,
                opcode.CALL, 0xF8, 0xFF) // -8 -> JMP to TOALTSTACK)                                                                                                                                                                                                                                                   
}

func TestInvocationLimitGood(t *testing.T) {
        prog := callNTimes(MaxInvocationStackSize - 1)
        v := load(prog)
        runVM(t, v)
}

func TestInvocationLimitBad(t *testing.T) {
        prog := callNTimes(MaxInvocationStackSize)
        v := load(prog)
        checkVMFailed(t, v)
}
```
The only inconvenience (if you're to forget about `opcode.` that is trivial to remove) is that you have to be careful with instruction parameters. Still it's a bit easier to read and maintain than something like
```
            "script": "0x682953797374656D2E457865637574696F6E456E67696E652E476574536372697074436F6E7461696E657282",
```

**Comment by roman-khimov** [comment]
At the same time I understand that for JSON this needs to be changed somehow, and preferably without a need to parse some assembler format (although that's tempting), maybe using mixed-typed array like
```
{
   "script" : [
      "PUSHBYTES2", "0xff", 0,
      "TOALTSTACK",
      "DUPFROMALTSTACK",
      "JMPIF", 4, 0,
      "RET",
      "FROMALTSTACK",
      "DEC",
      "CALL", "0xF8", "0xFF"
   ]
}
```
I should be valid, not hard to produce real bytecode from and a little more maintainable than hexified binary.

**Comment by shargon** [comment]
I like it, but if we change the opcodes we will need to change again the opcodes, but it's easier to maintain. 

I can convert all the current jsons in something like this if you think that is a good format.

**Comment by erikzhang** [comment]
The `CAT.json` is huge.

**Comment by shargon** [comment]
> The CAT.json is huge.

We can accept base64 in order to reduce the size of some UT
