### ISSUE TITLE
[Feature] Convert ScriptHash to Address 

### ISSUE THREAD

**Issue by revett** [neo-project/neo-vm#26]
### Issue

An `Address` is converted to a `ScriptHash` when using [neo-python](https://github.com/CityOfZion/neo-python), which means that the `Address` cannot be stored as a **string** within `Storage`.

### Solution

Add ability to convert `ScriptHash` back to an `Address`.

**Comment by erikzhang** [comment]
Why we need to store a string address to storage?

**Comment by revett** [comment]
Thanks for the reply @erikzhang 👍

If you prefix the storage **key** with the user's **address** then they cannot alter any other user's storage:

For example:

```
ALZzNsLg5CaF1Qa2TSdWB1AawLxFUbKhHz.total_tokens => 3485
```

This is particularly important in [NeoAuth](https://github.com/neoauth/smart-contract) where login proofs are being stored in the contract.

You can read more about the issue in NeoAuth here: https://github.com/neoauth/whitepaper#limitations

**Comment by erikzhang** [comment]
What about just store the `ScriptHash`?

**Comment by revett** [comment]
@erikzhang So the storage action would be:

```
key:       <script_hash>.total_tokens
value:     3485
```

And then to read the storage value via the `getstorage` RPC call you would use the following as the `key` parameter:

```
<script_hash>.total_tokens
```

**But how can you translate `ScriptHash` into `Address` string?**

**Comment by erikzhang** [comment]
I don't think it's necessary to translate the address within the contract.
If you want to translate it outside of the contract, it is very easy. See https://github.com/neo-project/neo/blob/master/neo/Wallets/Wallet.cs#L391
