### ISSUE TITLE
[Feature Request] Hash table type

### ISSUE THREAD

**Issue by dicarlo2** [neo-project/neo-vm#27]
I'm currently working on a TypeScript/JavaScript -> NEO VM compiler and one thing that would be really handy is a native hash table type. While it's certainly possible to implement a hash table on top of the existing array functionality, it would be very script-space inefficient and GAS inefficient, requiring many op codes to properly access and manipulate the hash table. To that end, I propose we add 2 new types to the VM:

- `MapStackItem` which functions similarly to the `ArrayStackItem` 
- `DictStackItem` which functions similarly to the `StructStackItem` (that is, cloning in the same places `StructStackItem` is cloned).

### Terms:
 - **array-like**: Either a `ArrayStackItem` or `StructStackItem`
 - **map-like**: Either a `MapStackItem` or a `DictStackItem`
 - **stack item**: An arbitrary stack item
 - **key**: A stack item that can be used as a key. Only allows non-complex stack items, i.e. not an `ArrayStackItem`, `StructStackItem`, `MapStackItem`, or `DictStackItem`.

### New
 - `OpCode.NEWMAP`: Pushes a new `MapStackItem` onto the stack. Note that unlike `NEWARRAY`, an initial size is not set because it does not make sense in this context.
 - `OpCode.NEWDICT`: Pushes a new `DictStackItem` onto the stack. Similarly, does not have an initial size.
 - `OpCode.PICKMAPITEM`: Pops a key item `key` off the stack. Pops a map-like item `map` off the stack. Pushes `map[key]` onto the stack. If `key` does not exist, sets state to `FAULT`.
 - `OpCode.SETMAPITEM`: Pops a stack item `value` off the stack. Clones the value if it is a `StructStackItem` or `DictStackItem`. Pops a key `key` off the stack. Pops a map-like item `map` off the stack. Sets `map[key]` to `value`.
 - `OpCode.REMOVEMAPITEM`: Pops a key item `key` off the stack. Pops a map-like item `map` off the stack. Deletes `map[key]`. If `key` does not exist, does nothing.
 - `OpCode.HASMAPKEY`: Pops a key item `key` off the stack. Pops a map-like item `map` off the stack. Pushes `true` onto the stack if `key` is present in `map`, otherwise pushes `false`.
 - `OpCode.PACKMAP`: Pops an integer item `length` off the stack. Creates a `MapStackItem` and sets the items by popping a key item `key` off the stack and a stack item `value` off the stack `length` times. 
 - `OpCode.UNPACKMAP`: Pops a map-like item `map` off the stack. Unpacks `map` onto the stack in the same fashion that `OpCode.PACKMAP` expects.

### Changed
- `OpCode.ARRAYSIZE`: modified to get the size of a map-like item.
- `OpCode.APPEND`, `OpCode.SETITEM`: modified to additionally clone `DictStackItems`.

### Optional
These are nice to have, but not necessary given the above operations. However, they would help make certain operations more efficient and easier to manage, in particular `OpCode.MAPENTRIES` and `OpCode.ZIPMAP`.
 - `OpCode.MAPENTRIES`: Pops a map-like item `map` off the stack. Pushes an `ArrayStackItem` that is an array of tuple `ArrayStackItems` with `[key, value]` onto the stack. I.e. `Array<[key, value]`.
 - `OpCode.MAPKEYS`: Pops a map-like item `map` off the stack. Pushes an `ArrayStackItem` of the keys of `map`.
 - `OpCode.MAPVALUES`: Pops a map-like item `map` off the stack. Pushes an `ArrayStackItem` of the values of `map`.
- `OpCode.ZIPMAP`: Pops an array-like item `keys` off the stack. Pops an array-like item `values` off the stack. Zips them together and pushes a `MapStackItem` onto the stack.
 - `OpCode.UNZIPMAP`. Pops a map-like item `map` off the stack. Unzips the map in the same fashion that `OpCode.ZIPMAP` expects.

### Details

One minor detail is the implementation will need to add `hashCode` functionality and a custom comparator in order to have `StackItem` keys. `equals`, which would also be required, is already implemented.

**Comment by dicarlo2** [comment]
Hey @erikzhang I see that you added the enhancement label, does that mean we'll see this implemented soon?

**Comment by erikzhang** [comment]
I wonder if it should be an API to provide the functionality of a hash table.
Like this: `Neo.Utility.CreateHashTable`

**Comment by dicarlo2** [comment]
@erikzhang It could be a bunch of syscalls that map to the opcodes proposed above and I'm not opposed to making it a syscall, but to me it feels like something that should be native to the vm, similar to arrays. Either way, we would need to implement an `IEqualityComparer` for the `StackItem`s that are valid keys and it seems like for better future proofing it would make sense to implement it in the `neo-vm` project in case we add more `StackItem` types in the future.

**Comment by erikzhang** [comment]
We just need `MapStackItem`, right? I didn't see the necessity of `DictStackItem`.

**Comment by dicarlo2** [comment]
@erikzhang Yea, I just added `DictStackItem` for consistency with `StructStackItem`. If we don't add `DictStackItem` it might be nice to have an op code for shallow cloning a `DictStackItem`.

**Comment by dicarlo2** [comment]
@erikzhang Checking in, is this something that we'll see implemented as described in the spec? (Except for the `StructStackItem`)

This is a feature I'd like to make use of for the TypeScript compiler, so if you're planning on implementing it like the spec I'll go ahead and start developing against it.

**Comment by erikzhang** [comment]
Hi @dicarlo2 , please review #28 .

**Comment by localhuman** [comment]
This is awesome, adding support in `neo-python` now.  Not sure how I missed it!

@erikzhang @dicarlo2 do you have any sample `.avm` I can use to test with?

**Comment by dicarlo2** [comment]
@localhuman Sorry, a little late on the reply (cleaning up notifications). I do not currently have a sample `.avm` to test with, I just tested using manual unit tests.
