### ISSUE TITLE
New type: Buffer

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo-vm#271]
If you want to use `ByteArray` as a key of `Map`, it must be immutable. Otherwise it will lead to non-deterministic behavior.

Maybe we should design a new type `Buffer`. It is a mutable type and is not allowed to be a key of a `Map`. You can use any opcode for accessing `Array` to read and write the `Buffer`. It differs from `Array` in that it does not have a limit of 2048 elements.

Then we should have a new opcode: `CONVERT`, to allow the script convert items to another type.

**Comment by shargon** [comment]
I was thinking about it and we need ByteArray as inmutable, imagine something like this:

```csharp
Transfer(value)
{
var data =(BigInteger)Storage.Get(0x01);
Call(otherContract,data);
data-=value;
Storage.Put(0x01,value);
}
```

An atacker could alter the expected behavior of the contract, so I Think that if we want a mutable type for byte arrays, we need another typer, as you said, Buffer is good to me

**Comment by lock9** [comment]
One question: why it doesn't need the limit?
