### ISSUE TITLE
Pointer questions

### ISSUE THREAD

**Issue by shargon** [neo-project/neo-vm#277]
Currently we check the limits when we create the `Pointer` at 

https://github.com/neo-project/neo-vm/blob/127521afe1abd1dd508a7cfd6e1c43683ae2b89e/src/neo-vm/ExecutionEngine.cs#L119

But also we do this check when we call this `Pointer`

https://github.com/neo-project/neo-vm/blob/127521afe1abd1dd508a7cfd6e1c43683ae2b89e/src/neo-vm/ExecutionEngine.cs#L92

I think that we should check it only when we call it, because maybe we send this pointer to other context.

So the question are:

- Shall we remove the check in `PUSHA` ?
- Shall we check that the Script are the same in `CALLA` and `PUSHA` in order to prevent to use a pointer in different context (Script)?

**Comment by erikzhang** [comment]
> Shall we check that the Script are the same in CALLA and PUSHA in order to prevent to use a pointer in different context (Script)?

Yes!
