### ISSUE TITLE
new Buffer type questions

### ISSUE THREAD

**Issue by ixje** [neo-project/neo-vm#281]
From #271 I learned that `Buffer` is intended to be the immutable counter part of `ByteArray`. The issue and implementation left me with 2 questions. 

1. Why is the size not limited? (as asked by @lock9 https://github.com/neo-project/neo-vm/issues/271#issuecomment-566165865). 

   It looks to me that a limit would at least provide a speed benefit in the `GetHashCode()` function.
https://github.com/neo-project/neo-vm/blob/b7e0a3a15c3b120152d528bdb683deb213249dbd/src/neo-vm/Types/PrimitiveType.cs#L43-L44

   Also if I do this
   ```
   Neo.VM.Types.Buffer b = new Neo.VM.Types.Buffer(int.MaxValue);
   ```
   I get an `out of memory` error. I currently do not see what would stop this from being done via a smart contract (thus creating a DOS issue). 

2. Why is the `ToBoolean` function hardcoded to `true` instead of being dynamic like its `ByteArray` mutable counter part?
https://github.com/neo-project/neo-vm/blob/b7e0a3a15c3b120152d528bdb683deb213249dbd/src/neo-vm/Types/PrimitiveType.cs#L55-L59

**Comment by shargon** [comment]
> Why is the size not limited? (as asked by @lock9 #271 (comment)).

Size it will be limited here https://github.com/neo-project/neo-vm/blob/b7e0a3a15c3b120152d528bdb683deb213249dbd/src/neo-vm/ExecutionEngine.cs#L559 
https://github.com/neo-project/neo-vm/blob/b7e0a3a15c3b120152d528bdb683deb213249dbd/src/neo-vm/ExecutionEngine.cs#L583

> Why is the ToBoolean function hardcoded to true instead of being dynamic like its ByteArray mutable counter part?

It's for speed, but I think that we can remove this an cache the result.

**Comment by ixje** [comment]
Thanks for the size links @shargon 👍 

> It's for speed, but I think that we can remove this an cache the result.
Caching sounds good. How about caching the result `GetHashCode()` from point 1.? In the worse case the max size causes a loop over 1048576 bytes

**Comment by shargon** [comment]
> I get an out of memory error. I currently do not see what would stop this from being done via a smart contract (thus creating a DOS issue).

@ixje are you able to replicate this issue?
