### ISSUE TITLE
JMPDEST Opcode

### ISSUE THREAD

**Issue by shargon** [neo-project/neo-vm#287]
What do you think about create a specific opcode for allow the offset as jump destination?
Ethereum have this and I think that it's a good practice, now, we can jump in a `Operand` content of other opcode.

This could avoid compiler issues, and also it's better for parsers, because you can ensure that if you read the NEF file sequencial, you will have all the opcodes and the flow execution, otherwise, a JMP can alter any sequence and make harder the reversing of the execution.

**Comment by lightszero** [comment]
I don't think so,It is hard to read NEF file however.
why not Add a Better DASM tool to show it
