### ISSUE TITLE
[DynamicAppCall] GetCallingScriptHash can only be called from Main

### ISSUE THREAD

**Issue by ixje** [neo-project/neo-vm#29]
Let me start by explaining my interpretation of the function named [GetCallingScriptHash](https://github.com/neo-project/neo-vm/blob/master/src/neo-vm/InteropService.cs#L41) and perhaps we can already stop there if that's wrong.

When I think of `GetCallingScriptHash` then I believe that it will return the script hash of whoever is calling the smart contract this function is used in. 2 examples of that:

1. `wallet 1` calls `Contract A`, and `Contract A` uses `GetCallingScriptHash` -> I expect the script hash of `Wallet 1`.

2. `Contract A` DynamicAppCalls `Contract B`, and `Contract B` uses `GetCallingScriptHash`  -> I expect it to return the script_hash of `Contract A`.

If that _is_ the expected behaviour then `GetCallingScriptHash` is currently limited to be called from the `Main` function of the dynamically called contract. The question is; is this intentional, a bug or something that needs enhancement?

Let me elaborate on that with an example

```
Contract A:
def Main():
   dynamicappcall -> contract B
```   

```
Contract B:
def Main()
     function_x()

def function_x:
    GetCallingScriptHash()
```

The invocation stack frames  are as follows;
0 -> the argument list provided on the console to the contract
1 -> Contract_A.Main
2 -> Contract_B.Main
3 -> Contract_B.function_x

Now; `GetCallingScriptHash` does `InvocationStack.peek(1)` (or basically takes the second last item of the invocation stack). That means it will return the script_hash of frame [2] which is `Contract_B`, not `Contract_A` (frame [1]) as the function name suggests.

**Comment by erikzhang** [comment]
Yes, this is the expected behavior. If you need to get the calling contract, invoke `GetCallingScriptHash` at `Main`.
