### ISSUE TITLE
Why this script execution is 'HALT'?

### ISSUE THREAD

**Issue by hactrox** [neo-project/neo-vm#297]
The script of txID **0x66e79b67f31fe861287e2921c796381a3af5ee0b2c05085cf734da4c1d436187** on mainnet is:
```
060008352d8d0d14bbcd0b448d8320a61f3ee6060ba8eae8985211131418508cd218ecd52e00ea729d599246150b61079a53c1087472616e7366657267c0b5342fae238da8c0268a469cc86f99ab89c081f166e6497d3e76a0debf
```
The human-friendly format is:
```
06 0008352d8d0d
14 bbcd0b448d8320a61f3ee6060ba8eae898521113
14 18508cd218ecd52e00ea729d599246150b61079a
53 c1
08 7472616e73666572
67 c0b5342fae238da8c0268a469cc86f99ab89c081
f1
66e6497d3e76a0debf
```

It's a regular nep5 transfer script except the last part, the execution of `66e6497d3e76a0debf` should be `FAULT`, but why in fact it be `HALT`?

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo-vm/blob/30e9d573d1fcad40a21f6ee14d7eb9703a8a6d10/src/neo-vm/OpCode.cs#L119-L122

Because `0x66` is `RET`.

**Comment by hactrox** [comment]
My bad, should switch to `master-2.x` branch.
