### ISSUE TITLE
Add ASSERT opcode

### ISSUE THREAD

**Issue by Tommo-L** [neo-project/neo-vm#299]
`Assert` can increase contract usage security, such as it can be used to prevent reentry attacks, safe math library, etc.

**Comment by Tommo-L** [comment]
Another benefit is that we can use `Assert` to replace `throwifnot` in the wallet. So we can directly modify the parameters of `throw` instruction to support exception error.

https://github.com/neo-project/neo/blob/a8eca7095264fcfc9045d6887bfc9408e6a5d5a4/src/neo/Wallets/Wallet.cs#L255-L259

**Comment by shargon** [comment]
I think that it's a good idea, but as `SYSCALL`

**Comment by erikzhang** [comment]
What's the difference between `ASSERT` and `THROWIFNOT`?

**Comment by Tommo-L** [comment]
When `ASSERT` failed, it wil exit exeuction. When `THROWIFNOT` passed, it'll throw an exception in vm, which can be catched.

Another reason is that we want to adjust the parameters of `throw`:
```js
throw Exception
throwif/throwifnot boolean, Exception
```

**Comment by erikzhang** [comment]
If so, we should remove `THROWIF` and `THROWIFNOT`. What do you think?

**Comment by Tommo-L** [comment]
It's good for me, `throw` is enough now.

**Comment by Tommo-L** [comment]
@shargon  why `SYSCALL` ?

**Comment by shargon** [comment]
Because is something easier to implement and extend in the future, VM should be more stable
