### ISSUE TITLE
WITHIN opcode implementation question

### ISSUE THREAD

**Issue by ixje** [neo-project/neo-vm#301]
https://github.com/neo-project/neo-vm/blob/754bca3568c50695c571cb796c500fd66c07d0fe/src/neo-vm/ExecutionEngine.cs#L835-L841

Say our range is `[1,2,3,4]`, if we test the boundaries of the range we get
1. `a=1, b=4, x=1` WITHIN => `True`
2. `a=1, b=4, x=4` WITHIN => `False`

Should the upper bound check not be `x <= b` instead of `x < b`, such that the upper bound test actually returns `True`?

**Comment by shargon** [comment]
I think that it should be changed, yes, 4 is inside.

**Comment by erikzhang** [comment]
No. It is in the range `[a, b)`.

**Comment by Tommo-L** [comment]
Personally, I think it is important to keep the semantic consistency. In other languages, such as SQL, the `within` contains both a and b.

**Comment by Tommo-L** [comment]
If we want to express whether it's between a and b(excluded), how about renaming it `BETWEEN` , just like in SQL.

**Comment by shargon** [comment]
I think the same as @Tommo-L

**Comment by erikzhang** [comment]
In fact, this opcode is copied from bitcoin.

https://en.bitcoin.it/wiki/Script#Arithmetic

**Comment by ixje** [comment]
Historically Bitcoin has made more mistakes. I hope we're not copying those when we're aware of them in time.
