### ISSUE TITLE
SETITEM for buffer, implementation typo?

### ISSUE THREAD

**Issue by ixje** [neo-project/neo-vm#302]
https://github.com/neo-project/neo-vm/blob/754bca3568c50695c571cb796c500fd66c07d0fe/src/neo-vm/ExecutionEngine.cs#L1076-L1077

I want to double check if the lower bound validation is intended to be on `sbyte.MinValue` (signed byte)? 

I assume it should be `byte.MinValue` given that the second check is also on `byte.MaxValue`, but there might be some special reason for this that I can't deduce from the code.

**Comment by erikzhang** [comment]
It support both `sbyte` and `byte`. So the range is:

```
[-128, 127] U [0, 255] = [-128, 255]
```

**Comment by ixje** [comment]
Ok so it is intentional. Thanks.
