### ISSUE TITLE
Implement hashcode in CompoundType

### ISSUE THREAD

**Issue by Tommo-L** [neo-project/neo-vm#306]
If we implement the `hashcode` method in `CoumpoundType`, then we can use `map<StackItem, StackItem>`, and remove `Buffer` which is too unfriendly for compilers.

Some methods to implement hashcode:
- option1: use momeory address hash
- option2: use self-increasing sequences
- ~option3: use content hash~
....

**Comment by erikzhang** [comment]
I don't understand how to remove `Buffer`.

**Comment by Tommo-L** [comment]
> If you want to use ByteArray as a key of Map, it must be immutable. Otherwise it will lead to non-deterministic behavior.  

As discussed at #271 ,  if we change the ByteArray, we'll get a new hashcode, as `PrimitiveType.hashcode` is related to content.

For me, I think ByteArray is `CoumpoundType`, not `PrimitiveType` just like c# `byte[]`. Here is a c# example about `byte[]`:

```cs
Dictionary<byte[], int> map = new Dictionary<byte[], int>();

var k1 = new byte[] { 0x00, 0x01 };
var k2 = new byte[] { 0x01, 0x01 };
map[k1] = 1;
map[k2] = 2;

System.Console.WriteLine("before map[k1]: " + map[k1] + "\t k1 hashcode: " + k1.GetHashCode());
System.Console.WriteLine("before map[k2]: " + map[k2] + "\t k2 hashcode: " + k2.GetHashCode());

k1[0] = 0x01;
k2[0] = 0x00;

System.Console.WriteLine("after map[k1]: " + map[k1] + "\t k1 hashcode: " + k1.GetHashCode());
System.Console.WriteLine("after map[k2]: " + map[k2] + "\t k2 hashcode: " + k2.GetHashCode());
```
outputs:

```
before map[k1]: 1	 k1 hashcode: 21358135
before map[k2]: 2	 k2 hashcode: 45867655
after map[k1]: 1	 k1 hashcode: 21358135
after map[k2]: 2	 k2 hashcode: 45867655
```

**Comment by erikzhang** [comment]
No. `ByteArray` is immutable. `Buffer` is the c# `byte[]`.

**Comment by Tommo-L** [comment]
Why? Is there any other place where we need to keep the ByteArray immutable? And do we need to support the hashcode in CoumpoundType?

**Comment by Tommo-L** [comment]
Hi, @ixje  since you are writing neo-python, do you have a similar problem with `ByteArray` and `Buffer`. For example, `bytes.reverse`, `bytes[i] = a`, which we must convert to `Buffer` before.

**Comment by ixje** [comment]
@Tommo-L sorry for the late reply, I have very limited availability until next week. 

As for your question. I basically do a 1:1 port of `neo-vm` because it is the easiest way to be compliant with a moving target and without having a standard to describe the vm. Having said that, we treat ByteArray vs Buffer as described by Erik here https://github.com/neo-project/neo-vm/issues/306#issuecomment-604859561

**Comment by Tommo-L** [comment]
@ixje Thanks, we have also compiled c# byte[] to Buffer now.
