### ISSUE TITLE
Could we add REVERSE opcode

### ISSUE THREAD

**Issue by Tommo-L** [neo-project/neo-vm#307]
Since we have `CAT`,  `SUBSTR`, `LEFT`, `RIGHT` for bytes, but we lost `REVERSE` for bytes. I know we already have `REVERSEITEMS`, but it's for `Neo.VM.Types.Buffer`.  In compiler, we want to reverse a byte array, and put the result on the eval stack.  At present, we handle it by this way in compiler, which take a lot of work.

```cs
/// <summary>
/// Returns a reversed copy of byte[] parameter 'source' (parameter is not affected because byte[] is copy-based on NeoVM).
/// Example: [0a,0b,0c,0d,0e] -> [0e,0d,0c,0b,0a]
/// </summary>
public static byte[] Reverse(this byte[] source)
{
	for (int k = 0; k < source.Length / 2; k++)
	{
		int m = source.Length - k - 1;
		byte bg = source[k]; // must store on variable before next assignment
		byte ed = source[m]; // must store on variable before next assignment
		source[k] = ed;
		source[m] = bg;
	}
	return source;
}
```

**Comment by ShawnYun** [comment]
Agree. Now using `Helper.Reverse()` also causes some compilation problems.

**Comment by shargon** [comment]
Ok for me, but the cost of this opcode has to depend on size.

**Comment by erikzhang** [comment]
Why do you need it?

**Comment by Tommo-L** [comment]
If possible, we'll add it. Since we already have `CAT`, `SUBSTR`, `LEFT`, `RIGHT` for `String` and `Buffer`. we need `REVERSE` for both too. 😂

**Comment by erikzhang** [comment]
Please explain first why you need it?

**Comment by Tommo-L** [comment]
We want to support the reverse operation in compiler for Buffer/String. Currently, we only have `REVERSEITEMS` opcode, which is for Buffer. I know we'll support `Buffer` in contract finally, just step by step. 😂

**Comment by Tommo-L** [comment]
Since compiler convert c# byte[] to vm Buffer, we don't need this opcode now.
