### ISSUE TITLE
Is it necessary to rename ByteArray?

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo-vm#308]
Since `ByteArray` is immutable, maybe we should rename it to `String`. What do you think? @neo-project/core

**Comment by shargon** [comment]
`String`, `ByteChunk` or `FixedBuffer` it's good to me

**Comment by ixje** [comment]
> `String`, `ByteChunk` or `FixedBuffer` it's good to me

Out of the suggestions I like `FixedBuffer`. Alternatively I'd suggest `ImmutableBuffer`. 
The `Fixed` part of `FixedBuffer` could refer to the length. `ImmutableBuffer` is unambiguous.

**Comment by ixje** [comment]
nm, didn't see the PR before commenting.
