### ISSUE TITLE
Create Decimal Type

### ISSUE THREAD

**Issue by shargon** [neo-project/neo-vm#312]
I think that we will need Decimal type inside the VM, in order to be full compatible with the json standard, otherwise, the json syscalls could be less powerfull than expected. For example you cant parse this json if you want to get the name.

```json
{"name":"BTC","price":10000.56}
```

According to: https://github.com/neo-project/neo/pull/1588#discussion_r410869127

**Comment by erikzhang** [comment]
Agree.

**Comment by erikzhang** [comment]
@shargon Do you still think it is useful, since we are not filtering in the contract?

**Comment by shargon** [comment]
Currently we can deal with it because the json path can get the value
