### ISSUE TITLE
MEMCPY.json in Tests/ is not a valid JSON

### ISSUE THREAD

**Issue by fyrchik** [neo-project/neo-vm#322]
It has `//` comments which are not permitted by JSON specification.
https://github.com/neo-project/neo-vm/blob/master/tests/neo-vm.Tests/Tests/OpCodes/Splice/MEMCPY.json

**Comment by ixje** [comment]
Perhaps this is a good moment to revive https://github.com/neo-project/neo-vm/pull/94 and agree on a standard to enforce for NEO3? We can use a json schema + validator to make sure all json files pass.

Other items I'd like to include:
* not all tests have a `name` field (e.g. TRHOW, ABORT,ASSERT, PUSHM1_to_PUSH16, PUSHINT8_to_PUSHINT256.json)
* hex strings are sometimes prefixed with `0x` and sometimes not. Let's just fix them in some format (either with or without)
* Restrict elements in the list under the `script` key to be either an instruction name or a hex string. Not "PUSH0*1048576" like `CAT.json` has.
