### ISSUE TITLE
Primitive type comparison failure

### ISSUE THREAD

**Issue by ixje** [neo-project/neo-vm#330]
When comparing 2 different primitive types we end up calling
https://github.com/neo-project/neo-vm/blob/57519e2e25bc39c944f8e691d16e8a257770c82e/src/neo-vm/Types/PrimitiveType.cs#L35

This would be fine if the ReadOnlyMemory is set _equally_ on all derived types, but it is not. See the following test

```C#
            var i0 = new Integer(0);
            var i1 = new Integer(1);
            var i2 = new Integer(new BigInteger(new byte[] {0x1, 0x2}));

            var b0 = new Neo.VM.Types.ByteArray(new byte[]{0x0});
            var b1 = new Neo.VM.Types.ByteArray(new byte[]{0x1});
            var b2 = new Neo.VM.Types.ByteArray(new byte[]{0x1,0x2});
            
            var bsi_false = new Neo.VM.Types.Boolean(false);
            var bsi_true = new Neo.VM.Types.Boolean(true);
            Console.WriteLine("Boolean equals Integer");
            Console.WriteLine($"expected: True actual: {bsi_false.Equals(i0)}");
            Console.WriteLine($"expected: True actual: {bsi_true.Equals(i1)}");
            Console.WriteLine($"expected: False actual: {bsi_true.Equals(i2)}");
            Console.WriteLine("Boolean equals ByteArray");
            Console.WriteLine($"expected: True actual: {bsi_false.Equals(b0)}");
            Console.WriteLine($"expected: True actual: {bsi_true.Equals(b1)}");
            Console.WriteLine($"expected: False actual: {bsi_true.Equals(b2)}");
```
results in
```
Boolean equals Integer
expected: True actual: False <-- WRONG
expected: True actual: True
expected: False actual: False

Boolean equals ByteArray
expected: True actual: True
expected: True actual: True
expected: False actual: False

```

A `0`  `Integer`  should equal a `false` `Boolean` stack item, and also equal a `ByteArary` with 1 `0x00`  byte

-----
So we get back to the good old discussion on how should `false` or `0` be represented in byte array format. Here the NEO team agreed that a `Boolean(false)` should return `0x00` (https://github.com/neo-project/neo-vm/issues/129, https://github.com/neo-project/neo-vm/pull/132) for `3.x`. The same people that were in favour for the `Boolean` stack item, are against the same idea for the `Integer`  stack item (https://github.com/neo-project/neo-vm/issues/289).

My opinion is still that this is the root cause:
https://github.com/neo-project/neo-vm/blob/57519e2e25bc39c944f8e691d16e8a257770c82e/src/neo-vm/Types/Integer.cs#L16

I see 2 solutions:
1) change `Boolean`  `false`  to return `ReadOnlyMemory<byte>.Empty` and create a special case in PrimitiveType for handling a `ByteArray` (and possible future PrimitiveType derivatives) e.g.

```C#
        public virtual bool Equals(PrimitiveType other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other.Type == StackItemType.ByteArray && other.Size == 1 && other.Span[0] == 0x00)
                return Span.SequenceEqual(ReadOnlySpan<byte>.Empty);
            return Span.SequenceEqual(other.Span);
        }
```
2. change `Integer` to return `0x00` for a `0` value and fix the garbage collection issue mentioned (here https://github.com/neo-project/neo-vm/issues/289#issuecomment-593544878) at the root in the core project instead of in the VM.

**Comment by erikzhang** [comment]
> expected: True actual: False <-- WRONG

Why do you think it should be `true`?

**Comment by ixje** [comment]
Fair question; because for the languages I know (C, C++, JavaScript & Python) this holds true. It also logically makes sense when the following statements both produce `0x00`
```C#
            var bigint_bytes = new BigInteger(0).ToByteArray();
            var bool_bytes = BitConverter.GetBytes(false);
```
in combination with the `Integer` and `Boolean` stack items just being wrappers around the former 2 types.

**Comment by ixje** [comment]
@erikzhang I'd like to ask the reverse, if we ignore the mentioned garbage collection issue, why should it not be True knowing that `Boolean True == Integer 1`, `Integer 1 == ByteArray 0x01` and `Bool false == ByteArray 0x00` ?

To me the only deviation in the whole logic tree here is `Integer 0 != ByteArray 0x00` and `Integer 0 != Bool false`

**Comment by erikzhang** [comment]
If you need the result `true`, you need to use the `NUMEQUAL`.

**Comment by ixje** [comment]
I'm not necessarily looking for a workaround. I'm trying to understand _why_ this non-standard approach was chosen. It even deviates from the C# language on the byte array conversion side as shown above. It looks like this behaviour/implementation was chosen to resolve a garbage collection issue somewhere in the core, but I don't know if this is the actual reason.

**Comment by erikzhang** [comment]
For `EQUAL`, I think maybe we should modify it to return `false` if the types are not the same. @ixje What do you think?

**Comment by ixje** [comment]
If that means changing `Equals()` for all `PrimitiveType's` to return false if they're not of the same type then I'd be in favour. 

The nice secondary effect of doing the above is that it makes equality checking concise between `ByteString` and `Buffer`. It is my understanding that `ByteString` is the immutable version of `Buffer` (which is mutable)`. However, right now `ByteString` _can_ be compared to `Integer` and `Boolean` and has cases that can evaluate to true, whereas `Buffer` will always return `false` when comparing to `Integer` or `Boolean`.

**Comment by ixje** [comment]
Having written the above actually raises another question; 
If ` ByteString` and `Buffer` only differ in mutability, then why is `Buffer` not also a `PrimitiveType`?

**Comment by shargon** [comment]
> For EQUAL, I think maybe we should modify it to return false if the types are not the same. What do you think? @ixje @shargon

Agree, it could be like === or == in typescript

**Comment by erikzhang** [comment]
> If ByteString and Buffer only differ in mutability, then why is Buffer not also a PrimitiveType?

Because `PrimitiveType` is immutable.

**Comment by ixje** [comment]
I'm thinking that if `ByteString` and `Buffer` are each others counter parts, then their behaviour should be identical except in the areas related to mutability. e.g. the immutable version can't modify in place, but could return a copy instead. Other functions like equality, size etc should be identical for both types with the same, do you agree @erikzhang , @shargon ? 

Note that this is currently not the case for `ByteString` and `Buffer` in the following areas

```
+-------------------+---------------+-------------------+---------------------------------------------------------------------------+
|                   |    Buffer     |    ByteString     |                                  Comment                                  |
+-------------------+---------------+-------------------+---------------------------------------------------------------------------+
| Equals other type | always false  | true or false (1) | 1) if other obj is also PrimitiveType then depends on internal byte array |
| ToBoolean()       | always true   | true or false (2) | 2) depends on internal bytearray                                          |
| ToBigInteger()    | not supported | supported         |                                                                           |
| ToInt32()         | not supported | supported         |                                                                           |
+-------------------+---------------+-------------------+---------------------------------------------------------------------------+
```

While e.g. in C# it does work like that
```C#
List<byte> l = new List<byte>();
l.Add(0x1);
l.Add(0x2);
ImmutableList<byte> il = ImmutableList<byte>.Empty;
il = il.Add(0x1);
il = il.Add(0x2);
Console.WriteLine(il.Equals(l)); // true
```
and for Python the same
```python
In [1]: immutable = bytes.fromhex('AABB')                                       
In [2]: muttable = bytearray.fromhex('AABB')                                    
In [3]: immutable == muttable                                                   
Out[3]: True

```

**Comment by erikzhang** [comment]
> Console.WriteLine(il.Equals(l)); // true

This should be `false`.

**Comment by shargon** [comment]
I think that the conversions should be the same for Buffer and ByteString

**Comment by erikzhang** [comment]
I think you can think of them as the relationship between `string` and `StringBuilder`.

**Comment by ixje** [comment]
> > Console.WriteLine(il.Equals(l)); // true
> 
> This should be `false`.

😕 I don't know what output window I was looking at, but checking again it is indeed `False`. I thought `Equals` to be by value, whereas `==` is by reference. I guess not.

**Comment by ixje** [comment]
**Discussion summary**
I believe the summary of the issue is
- Change primitive types to return `False` if compared to a different type ([ref](https://github.com/neo-project/neo-vm/issues/330#issuecomment-637999406)). 

    In favour; all
- Add `ToBigInteger()` and `ToInt32()` support to `Buffer`, change `ToBoolean()` of `Buffer` to produce the same results as `ByteString` ([ref](https://github.com/neo-project/neo-vm/issues/330#issuecomment-638260861)). 

    In favour; shargon + ixje. 
Erik; unknown
