### ISSUE TITLE
Could we save the exception for neo-node/rpc

### ISSUE THREAD

**Issue by Tommo-L** [neo-project/neo-vm#331]
I think we'd better save the unhandled exception for neo-node/rpc, they should have some way to learn about them.

https://github.com/neo-project/neo-vm/blob/9d02720044d161c2a334d8e5a66130d3feda4066/src/neo-vm/ExecutionEngine.cs#L1240-L1250

**Comment by ixje** [comment]
Is your idea to throw it up the chain or allow them to retrieve it from the engine?

**Comment by Tommo-L** [comment]
> Is your idea to throw it up the chain

No,

> allow them to retrieve it from the engine?

Yes
