### ISSUE TITLE
Convert byte[] to Buffer?

### ISSUE THREAD

**Issue by Tommo-L** [neo-project/neo-vm#338]
In c# contract, we convert `byte[]` to Buffer, and `string` to ByteSting. Let's keep in consistent?

https://github.com/neo-project/neo-vm/blob/22b683c57e267473d4e60818de0f0e9be8c0caeb/src/neo-vm/Types/StackItem.cs#L92-L96

**Comment by erikzhang** [comment]
This is the implementation of vm, not the same as the contract.

**Comment by Tommo-L** [comment]
Got.
