### ISSUE TITLE
SETITEM

### ISSUE THREAD

**Issue by shargon** [neo-project/neo-vm#34]
@erikzhang This instruction shouldn't be a Peek? if you pop the key, value and array, where goes the result?

https://github.com/neo-project/neo-vm/blob/b1338d488a4769938de648aaf7518a5f0c163afa/src/neo-vm/ExecutionEngine.cs#L753

Is necessary to clone first the array for call this opCode?

**Comment by erikzhang** [comment]
The array on the stack is just a reference. `SETITEM` has no result, it just changes the array. And every instruction should consume ALL the operands.
