### ISSUE TITLE
Possible bug in TRY/CATCH implementation

### ISSUE THREAD

**Issue by fyrchik** [neo-project/neo-vm#343]
Look at this test:
https://github.com/neo-project/neo-vm/blob/80168dd7d8773043b20da3350b7951cac31fb54b/tests/neo-vm.Tests/Tests/OpCodes/Control/TRY_CATCH.json#L6
We do 3 steps in a first round and end at the instruction 13. I believe we should end at 11-th instruction:
1) execute TRY (--> next is 3)
2) execute SYSCALL and jump to the CATCH block (--> next is 10)
3) execute one instruction from the CATCH block (PUSH1) (--> next is 11)

Another issue is that there is no CATCH block execution result (`BigInteger(1)`) in the final state.

We shouldn't execute `context.MoveNext()` after syscall has raised an exception i.e. jump was performed.

Related #339 .

**Comment by superboyiii** [comment]
@Tommo-L

**Comment by Tommo-L** [comment]
Waiting for me, I'll have a look.
