### ISSUE TITLE
Remove RET execution on PushOnly

### ISSUE THREAD

**Issue by shargon** [neo-project/neo-vm#35]
I think that is not necessary allow execute ' RET'  command while only push is allowed

https://github.com/neo-project/neo-vm/blob/b1338d488a4769938de648aaf7518a5f0c163afa/src/neo-vm/ExecutionEngine.cs#L56

What do you think @erikzhang ?

**Comment by erikzhang** [comment]
I think we can remove `PushOnly`. Can you evaluate the security if we remove `PushOnly` and allow all the instructions in `Neo.Core.Witness::InvocationScript`?

**Comment by shargon** [comment]
I do not really like the idea of removing `PushOnly` because it could cause them to execute any code without the need for a smartContract. I think that you can not eliminate `PushOnly`, What benefits could it bring?

I Asked by `RET` to avoid fattening the script with unnecessary code type

```
PUSH ORIGINAL_PARAMETERS
RET
PUSHBYTES...
PUSHBYTES...
PUSHBYTES...
PUSHBYTES...
PUSHBYTES...
```

And the execution is still valid, but it would make the chain fatter

**Comment by erikzhang** [comment]
The most direct advantage is that after removing `PushOnly`, we can use the instructions such as `NEWARRAY`, `NEWSTRUCT`, `PACK` to create parameters in `Neo.Core.Witness::InvocationScript`. And there's no reason to limit it now.

**Comment by shargon** [comment]
All this instructions are executed in a different ExecutionContext, so there is not possible to change storages of the contract. But could be used for invoke TXs and these TXs could create a different StorageContext for save arbitrary data

**Comment by erikzhang** [comment]
Contracts can't save any data if they are started with `Verification` trigger.

**Comment by erikzhang** [comment]
Currently, it is for `Verification` only.

**Comment by erikzhang** [comment]
@shargon Do you think it's ok to remove `PushOnly`?

**Comment by shargon** [comment]
Yes, it’s ok for me 👍
