### ISSUE TITLE
The question of comparing arrays

### ISSUE THREAD

**Issue by ProDog** [neo-project/neo-vm#363]
I'm trying to compare arrays in a contract.
case 1, it returns `false`.
```C#
            byte[] a1 = new byte[] { 0x01, 0x02 };
            byte[] a2 = new byte[] { 0x01, 0x02 };
            return a1.Equals(a2);
```

case 2, it execute `FAULT`, Error: `Specified cast is not valid`.
```C#
            byte[] a1 = new byte[] { 0x01, 0x02 };
            byte[] a2 = new byte[] { 0x01, 0x02 };
            return a1 == a2;
```

Do we now support array comparisons?

**Comment by erikzhang** [comment]
`byte[]` is a `Buffer` in NeoVM, which is incomparable. And `==` is for number comparison, so it should be used on `Integer` only.

`ByteString` is comparable, so you need to convert `byte[]` to `string` first.
