### ISSUE TITLE
Update Struct to have optional type information string

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-vm#366]
for more info, please see https://github.com/neo-project/neo/issues/1864

**Comment by Tommo-L** [comment]
As there is already a `Type` field in `Struct`, add `Name` field in `Struct`?

**Comment by devhawk** [comment]
> As there is already a `Type` field in `Struct`, add `Name` field in `Struct`?

That works for me.

**Comment by erikzhang** [comment]
Closed because it is no longer needed.
