### ISSUE TITLE
Returning static variable of type `Buffer` returns type `Any`

### ISSUE THREAD

**Issue by csmuller** [neo-project/neo-vm#368]
I deployed the following contract script. The manifest and NEF files for it can be found [here](https://github.com/neo-project/neo-vm/files/5239282/example-contract.zip).

```
INITSSLOT 01
PUSHDATA1 20 226730eaeec8e3315468f57153e3b08789cc45cc
STSFLD0
RET
LDSFLD0
RET
```
In the `INITSSLOT`, one static variable is set to a constant which I think will be represented as a `Buffer` or a `ByteString` on the VM. Thus, I expect it to return a stack item of type `Buffer`/`ByteArray`/`ByteString` when calling the `main` method. But what I get is a return type `Any`. 

If, on the other hand, I use the following script that does not use a static variable, the return type is not `Any` but `ByteString`.
```
PUSHDATA1 20 226730eaeec8e3315468f57153e3b08789cc45cc
RET
```

My questions: Is it intended behavior that static variables do not have a fixed `StackItemType`? Do I have to add a `CONVERT` opcode when using a static variable with `STSFLD`?

I ran everything with neo-node on tag `v3.0.0-preview3`.

**Comment by shargon** [comment]
I think that the problem is that you call `main` without call before `_initialize`.

https://github.com/neo-project/neo/blob/81ebb7d8def2ffbcd52120423f5de1bc9411578f/src/neo/SmartContract/ApplicationEngine.Contract.cs#L164-L165

**Comment by csmuller** [comment]
So, is `_initialize` something that needs to be called manually after deploying a contract?
When I do an invoke function to `_initialize` i get back `FAULT`.

Furthermore, if i deploy the following contract the call to the `main` method works - without calling `_initialize` first.
The only difference to my original example is the `CONVERT 30` opcode, which makes the variable a Buffer.
```
INITSSLOT 01
PUSHDATA1 20 226730eaeec8e3315468f57153e3b08789cc45cc
CONVERT 30
STSFLD0
RET
LDSFLD0
RET
```

**Comment by Tommo-L** [comment]
> So, is _initialize something that needs to be called manually after deploying a contract?  

@csmuller 

No, when you invoke the public method of contract (by using "System.Contract.Call/CallEx" syscalls), the `_initialize` will be automaticly called by neo-core/vm. 

> When I do an invoke function to _initialize i get back FAULT.

All "_xxxx" methods can't be invoked by mannually, these are some special methods:
- ["_initialize" is for initialize the static variable of contract](https://github.com/neo-project/neo/blob/master/src/neo/SmartContract/ApplicationEngine.Contract.cs#L183)
- ["_deploy" is for contract initialization, when contract is created or updated by "System.Contract.Create/Update"](https://github.com/neo-project/neo/blob/master/src/neo/SmartContract/ApplicationEngine.Contract.cs#L60)
- ["verify" is for transaction verification, when contract as the signer](https://github.com/neo-project/neo/blob/master/src/neo/SmartContract/Helper.cs#L165)

**Comment by csmuller** [comment]
Thanks for the clarifications. By the results in #375, this issue is also resolved.
