### ISSUE TITLE
Neo-vm returns ANY when invoking a script at an address that is outside of its bounds

### ISSUE THREAD

**Issue by csmuller** [neo-project/neo-vm#376]
**Summary or problem description**
The scenario is that a contract manifest has a faulty offset to a method. The offset points outside of the contract script's bounds. When deployed and invoked the neo-vm returns a null StackItem of type ANY and in state HALT. 

**Do you have any solution you want to propose?**
In my opinion it is more reasonable and less confusing to return FAULT in such a scenario.
Additionally, as a developer making a `invokefunction`, call it is desirable to receive more information about why the neo-vm faulted. But that is not the main concern of this issue.

**Comment by roman-khimov** [comment]
> it is desirable to receive more information about why the neo-vm faulted

neo-project/neo-modules#334
