### ISSUE TITLE
is switching to .NET 5 a good idea?

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-vm#379]
@erikzhang I see you just [committed](https://github.com/neo-project/neo-vm/commit/cf620066018deb01a9420e870999c1af53307984) a change that makes net5.0 the target framework for neo.vm. Is there a net5.0 feature that we're going to use in neo,vm? I was planning to keep blockchain toolkit managed apps on [.net 3.1 long term support release](https://dotnet.microsoft.com/platform/support/policy/dotnet-core)

**Comment by erikzhang** [comment]
I plan to use `record` in neo to rewrite the state classes.

**Comment by devhawk** [comment]
Are we doing this before preview 4?
