### ISSUE TITLE
JsonSerialize struct Error

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo-vm#404]
neither ByteString nor UInt160 is supported.

```cs
struct Pending
{
    public ByteString user;
    public BigInteger amount;
}
```

```cs
Pending returners = new Pending();
returners.user = bidder;
returners.amount = bidamount;
store[(ByteString)prefix_pendingReturns] = StdLib.JsonSerialize(returners);
```
![fc1ce1a30fa6e41ea0c3069e268863c](https://user-images.githubusercontent.com/34291844/113411824-581eab00-93e9-11eb-8158-f711f688332d.png)

**Comment by erikzhang** [comment]
For `ByteString`, we only support string.
For `BigInteger`, we only support integers that between `MIN_SAFE_INTEGER` and `MAX_SAFE_INTEGER`, which is `-9007199254740991` and `9007199254740991`.

**Comment by cloud8little** [comment]
> For `ByteString`, we only support string.
> For `BigInteger`, we only support integers that between `MIN_SAFE_INTEGER` and `MAX_SAFE_INTEGER`, which is `-9007199254740991` and `9007199254740991`.

since UInt160 type can be implicitly converted to ByteString, and it is 20 length bytes, but it can not be serialized. In my example, I input the bidder as UInt160 address hash, amount is 20.

**Comment by erikzhang** [comment]
We only support string. UInt160 is not supported.
