### ISSUE TITLE
Any chance of re-licensing or dual-licensing under Apache 2.0?

### ISSUE THREAD

**Issue by waywardgeek** [neo-project/neo-vm#41]
I am interested in exploring using this VM in an internal project at Google, but I know from experience that our lawyers will push back pretty hard if I try to import MIT licensed code, especially code in a hot space where there are lots of patents being filed.  The MIT license does not grant us any license to patents that might be filed by the authors of this code, and I've been told by lawyers that this creates an unacceptable risk before.  However, IANAL, so I could be wrong...

Any chance of re-licensing or dual-licensing to something that will give potential users more confidence that they can use this code without getting sued?

**Comment by lllwvlvwlll** [comment]
@erikzhang

**Comment by erikzhang** [comment]
Neo doesn't need any patents, but we don't have lawyers who are familiar with the business.
@waywardgeek Can your lawyer draw up an additional statement about the patent?

**Comment by waywardgeek** [comment]
I think the issue is that the NEO VM authors could file a patent, and then sue users of the NEO VM for patent infringement, even though the code is MIT licensed.  It is a wonky issue I never worried about before joining a large company that worries about such things.  If we could access the source code under an Apache 2.0 license, it would appease Google's lawyers.

**Comment by erikzhang** [comment]
Changing the license of the project can be unsuitable. Perhaps we can put an additional statement about the waiver of all patent rights in the project? @waywardgeek Can you consult your lawyer?

**Comment by igormcoelho** [comment]
If Apache is protective for Neo, I guess community would support dual license Erik.

**Comment by lock9** [comment]
Hello everyone.
This looks like the discussion is 'over' (we can't change the license, but we can add a statement).
I will close this and add this item to our monthly inbox.

**Comment by vncoelho** [comment]
Ricardo, I did not understand it like this.
The discussion was still open, but in an idle moment, there is no reason to close if an agreement (or final decision) was not yet reached.

**Comment by igormcoelho** [comment]
This decision is very important for Neo Foundation (that runs neo project). The risk is being sued by developers, that contributed code as MIT license, and somehow "withdraw" their rights.
This is a lawyer decision, some companies believe MIT license is "clear enough" to avoid these problems, but others think that Apache 2.0 is the solution.
Another point is that we need to have MIT license terms on every file (this is an absolute requirement of MIT license).

**Comment by steven1227** [comment]
> Neo can sue no one, and no one can sue Neo. Dual license MIT/Apache 2.0 seems nice to me.

Personally, I agree with this, @igormcoelho. Now, I am going to discuss this license problem with lawyers and find a solution as soon as possible.

**Comment by erikzhang** [comment]
> This decision is very important for Neo Foundation (that runs neo project).

This has nothing to do with NF. This should be decided by the core developer team.

**Comment by ixje** [comment]
> The risk is being sued by other developers, that contributed code as MIT license, and somehow "withdraw" their rights (or enter some private patent for their contributions).
There are 8 contributors on the `neo-vm` project. 6 of those are still daily active here on Github. Localhuman should be easy to reach, that leaves 1 who only committed the `README.md` and not code (I don't know if that matters). Can't be too hard to get an agreement on license swapping from all who've historically contributed.

**Comment by lllwvlvwlll** [comment]
@localhuman

**Comment by steven1227** [comment]
> > The risk is being sued by other developers, that contributed code as MIT license, and somehow "withdraw" their rights (or enter some private patent for their contributions).
> 
> There are 8 contributors on the `neo-vm` project. 6 of those are still daily active here on Github. Localhuman should be easy to reach, that leaves 1 who only committed the `README.md` and not code (I don't know if that matters). Can't be too hard to get an agreement on license swapping from all who've historically contributed.

I do not think this issue only in `neo-vm`. I found most repo in neo-project need to solve this license problem.

**Comment by igormcoelho** [comment]
I strongly vote for dual license `neo-vm` first, then the rest.
