### ISSUE TITLE
Nested Nested Nested Nested `StackItem`s could be Out Out Out Out of Memory Again in NeoVM

### ISSUE THREAD

**Issue by vang1ong7ang** [neo-project/neo-vm#426]
```
5601c501fe0360589d604a12c0db415824f7cd45
```

**Comment by roman-khimov** [comment]
> Combing nested nested Struct with `EQUAL` would be a better attack way. It will cost lots of time while not using too much memory.

`560112c501fe0160589d604a12c0db415824f7509d4a102aec4597`

**Comment by dusmart** [comment]
> `560112c501fe0160589d604a12c0db415824f7509d4a102aec4597`

Fantastic!
How about creating a pull request on <https://github.com/lazynode/Tanya>?
