### ISSUE TITLE
The source code  is not consistent.

### ISSUE THREAD

**Issue by sctxm** [neo-project/neo-vm#43]
The source code for Neo-VM and Neo is not consistent. 
For example: 
1, EvaluationStack is defined in the ExecutionContext class of Neo-VM, but it is used in the EvaluationStack class of Neo.
2, the loadScript function prototype defined in Neo-VM is “public ExecutionContext LoadScript (byte[] script, int rvcount = -1)”, and the call in Neo is engine.LoadScript(script, false)
3， and there are many other errors.
Please upload the latest stable version of NEO's source code to Github, thank you!

**Comment by birmas** [comment]
+1 to this - same issue. I'd like to debug some things I've found by linking the source of neo, neo-vm and neo-cli in a single project.

I can't currently do this due to the inconsistencies listed above.

**Comment by ixje** [comment]
I believe https://github.com/neo-project/neo-vm/issues/93 resolves this so this issue could be closed
