### ISSUE TITLE
Optimise the performance of VM with ObjectPool or reusing the existing objects.

### ISSUE THREAD

**Issue by Liaojinghui** [neo-project/neo-vm#431]
It is costly to create new Objects, but VM creates a lot of StactItem instances and abandons them once they are popped from the stack. If we could create Object pools for Types like `Integer` and `Boolean` (or even just reuse the existing objects of the same type instead of creating a new one every time we call `Push`), it would save a lot of memory (reduce GC probably) as well as objects creating time.

**Comment by Liaojinghui** [comment]
All cases include `engine` and `scriptbuilder` instantiation.

Intel Core i7-9750H CPU 2.60GHz, 1 CPU, 12 logical and 6 physical cores
.NET SDK=5.0.302
  [Host]     : .NET 5.0.8 (5.0.821.31504), X64 RyuJIT  [AttachedDebugger]
  DefaultJob : .NET 5.0.8 (5.0.821.31504), X64 RyuJIT


|                Method |     Mean |   Error |  StdDev |
|---------------------- |---------:|--------:|--------:|
|        Instruction_OR | 343.3 ns | 6.67 ns | 6.23 ns |
|  Instruction_OR_Reuse | 332.8 ns | 5.16 ns | 4.82 ns |
|       Instruction_AND | 350.8 ns | 6.70 ns | 8.23 ns |
| Instruction_AND_Reuse | 326.7 ns | 4.00 ns | 3.74 ns |
|       Instruction_XOR | 329.3 ns | 6.45 ns | 6.03 ns |
| Instruction_XOR_Reuse | 330.1 ns | 5.79 ns | 5.14 ns |

**Comment by shargon** [comment]
```csharp
[Benchmark]
        [ArgumentsSource(nameof(NonPrimitive))]
        public void Instruction_POW_Reuse(ExecutionEngine engine)
        {
            var a = (int)engine.Pop().GetInteger();
            engine.Limits.AssertShift(a);
            var b = (Integer)engine.Pop();
            b.Value = BigInteger.Pow(b.GetInteger(), a);
            engine.Push(b);
        }
```
`Peek` it's better, but how do you know that `b` was not `DUP`?

**Comment by Liaojinghui** [comment]
> ```csharp
> 
> [Benchmark]
> 
>         [ArgumentsSource(nameof(NonPrimitive))]
> 
>         public void Instruction_POW_Reuse(ExecutionEngine engine)
> 
>         {
> 
>             var a = (int)engine.Pop().GetInteger();
> 
>             engine.Limits.AssertShift(a);
> 
>             var b = (Integer)engine.Pop();
> 
>             b.Value = BigInteger.Pow(b.GetInteger(), a);
> 
>             engine.Push(b);
> 
>         }
> 
> ```
> 
> `Peek` it's better, but how do you know that `b` was not `DUP`?

Because the original code is Pop().GetInteger(), which means it's an integer stack item.

**Comment by Liaojinghui** [comment]
> ```csharp
> 
> [Benchmark]
> 
>         [ArgumentsSource(nameof(NonPrimitive))]
> 
>         public void Instruction_POW_Reuse(ExecutionEngine engine)
> 
>         {
> 
>             var a = (int)engine.Pop().GetInteger();
> 
>             engine.Limits.AssertShift(a);
> 
>             var b = (Integer)engine.Pop();
> 
>             b.Value = BigInteger.Pow(b.GetInteger(), a);
> 
>             engine.Push(b);
> 
>         }
> 
> ```
> 
> `Peek` it's better, but how do you know that `b` was not `DUP`?

Silly me, just realized that multiple items have the GetInteger implementation.
