### ISSUE TITLE
Shallow-copy problem for OrderedDictionary.CopyTo in case of Array & Map type

### ISSUE THREAD

**Issue by Qiao-Jin** [neo-project/neo-vm#433]
Func OrderedDictionary.CopyTo copies the content of an OrderedDictionary to a KeyValuePair array, by keys and corresponding values.

https://github.com/neo-project/neo-vm/blob/e1b06ed6d2c5a5e5e468686477ec344772b138a9/src/neo-vm/Collections/OrderedDictionary.cs#L95

In most cases it would be safe except when StackItem type is Array or Map, whose items can be set seperately. So problems can occur in such cases:

1. Copy the content of an OrderedDictionary to a KeyValuePair array
2. Change a value within a Map or Array item within the KeyValuePair array

Then the original value of the OrderedDictionary would also be changed.

**Comment by erikzhang** [comment]
But it's not used in any place, right?

**Comment by Qiao-Jin** [comment]
> But it's not used in any place, right?

Maybe we should delete this func?

**Comment by erikzhang** [comment]
The class implements `IDictionary<,>`. So we can't remove this method.

**Comment by Qiao-Jin** [comment]
> The class implements `IDictionary<,>`. So we can't remove this method.

+1

**Comment by Qiao-Jin** [comment]
Or should func DeepCopy be used here for future implementation?

**Comment by erikzhang** [comment]
We don't need to worry about it. Because it will never be used.

**Comment by Qiao-Jin** [comment]
> We don't need to worry about it. Because it will never be used.

OK
