### ISSUE TITLE
Add 'utf8Size' opcode 

### ISSUE THREAD

**Issue by lock9** [neo-project/neo-vm#437]
Hi,

The compiler / VM is not processing strings properly. It is always considering one byte per character, but this is not true for UTF-8 strings. We should probably add an 'utf8Size' opcode in addition to the current 'size' one. The compiler must use the correct opcode when dealing with strings.

There may be other places and opcodes to be added, like the 'substring' method (I don know how it is implemented, but I can confirm that it considers 1 byte per character).

Related to https://github.com/neo-project/neo-devpack-dotnet/issues/681

**Comment by shargon** [comment]
If we use another encoding we will have the same error

**Comment by lock9** [comment]
What do you mean by another encoding? We _only_ support UTF-8, right?

**Comment by erikzhang** [comment]
I'm not sure if it's necessary. Because it is also possible to operate by byte length.
