### ISSUE TITLE
Inconsistent return of BigInteger values upon Invocation

### ISSUE THREAD

**Issue by birmas** [neo-project/neo-vm#46]
This is a minimal example to show the issue of inconsistent returns for BigIntegers.

I came across this while making a modification to a NEP5 'balanceOf' implementation where wallets are expecting a ByteArray return for the value.
```
/*
test1: Evaluation Stack: [{"type":"Array","value":[]},{"type":"ByteArray","value":"40420f"}]
test2: Evaluation Stack: [{"type":"Array","value":[]},{"type":"Integer","value":"999900"}]
test3: Evaluation Stack: [{"type":"Array","value":[]},{"type":"Integer","value":"999900"}]
test4: Evaluation Stack: [{"type":"Array","value":[]},{"type":"ByteArray","value":"dc410f"}]
*/
using Neo.SmartContract.Framework;
using Neo.SmartContract.Framework.Services.Neo;
using System.Numerics;

namespace Neo.SmartContract
{
    public class Contract1 : Framework.SmartContract
    {
        public static object Main(string operation, params object[] args)
        {

            switch (operation)
            {
                case "test1":
                    return Test1();
                case "test2":
                    return Test2();
                case "test3":
                    return Test3();
                case "test4":
                    return Test4();
            }
            return false;
        }

        public static BigInteger Test1()
        {
            BigInteger blah = 1000000;
            return blah;
        }

        public static BigInteger Test2()
        {
            BigInteger blah = 1000000;
            BigInteger blah2 = blah - 100;
            return blah2;
        }

        public static byte[] Test3()
        {
            BigInteger blah = 1000000;
            BigInteger blah2 = blah - 100;
            return blah2.AsByteArray();
        }

        public static BigInteger Test4()
        {
            BigInteger blah = 1000000;
            BigInteger blah2 = blah - 100;
            Storage.Put(Storage.CurrentContext, "asdf", blah2);
            return Storage.Get(Storage.CurrentContext, "asdf").AsBigInteger();
        }
    }
}
```

**Comment by birmas** [comment]
I'm aware that they are the same values. The issue is with the inconsistent return types.

**Comment by erikzhang** [comment]
If a value is returned by an arithmetic instruction (such as `ADD` or `SUB`), it becomes an `Integer` type; Otherwise, it will keep the original data type. This is to optimize for big integers operations.
When a data is written to the store, its run-time type is lost because the store only records its value.

**Comment by birmas** [comment]
@erikzhang I see your point but consider the following example. Is it up to the caller of the contract then to determine whether to handle the return value of Test5() as a ByteArray or BigInteger? Depending on the value of "isTrue" it could return either a `ByteArray` or `Integer` even though the method return type is explicitly `BigInteger`

```
        public static BigInteger Test5()
        {
            BigInteger blah = 1000000;
            bool isTrue = Storage.Get(Storage.CurrentContext, "isTrue").AsBigInteger() > 0;
            if(isTrue) {
               return blah - 500;
             }
           return blah;
        }
```

**Comment by erikzhang** [comment]
If you handle it in a contract (in VM), then you don't have to do anything because VM automatically handles type conversions.
If you handle it outside of a VM, then you have to convert it by yourself.
Here is an example:
https://github.com/neo-project/neo-vm/blob/79c3aada150865036617fc4a785dbfe618c2e3b7/src/neo-vm/StackItem.cs#L30-L33

**Comment by birmas** [comment]
@shargon  has come up with a simple work around for this issue:
`userBalance.AsByteArray().Concat(new byte[] { }).AsBigInteger();` will force the return to be as expected by the wallets.

I will close this issue now because, as you say @erikzhang , wallets should be able to handle both Integer and ByteArray returns.

Thanks @shargon and @erikzhang for help.
