### ISSUE TITLE
How to customize an interface in interoperation service layer

### ISSUE THREAD

**Issue by lzszsd** [neo-project/neo-vm#472]
I am writing a Neo contract to access a kind of external data introduced in [https://docs.neo.org/v2/docs/en-us/assets/neovm.png](url). Specifically, the aim is to upload data from USB to the blockchain. The USB port is on the computer which the private chain and NeoVM are running upon. 

I have read the source code of NeoVM, but there is no instruction or comment on the issue. `public class InteropInterface`  seems to be instantiated in [https://github.com/neo-project/neo-vm/blob/master/src/neo-vm/Types/StackItem.cs](url), but it is not clear how the value in `_object = value ?? throw new ArgumentNullException(nameof(value));` and `return new InteropInterface(value);` determines the interface to be used. Should I learn more about C# or refer to some development documentation unknown to me?

**Comment by erikzhang** [comment]
You need to use an oracle. https://docs.neo.org/docs/en-us/advanced/oracle.html

**Comment by lzszsd** [comment]
Does the oracle support the USB service I mentioned? The docs says that URL is required for Oracle Request, but the two protocols it uses don't seem to apply to local USB communication. Any recommended material on how I can understand and customize Neo Oracle Service?

**Comment by erikzhang** [comment]
No. You must use https in oracle.
