### ISSUE TITLE
Presssure test on v3.3.0 cause execution failed

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-vm#477]
Presssure test on v3.3.0 cause execution failed.
Just send some txs by RPC, 10 works x 1 tx per second, continuously sending for a while, which can cause vm execution failed.
Node will stop syncing, restart can make recovery.
```
System.InvalidOperationException: 'Failed execution for 'CxEMFMCY5KzwsgkN0W7LPVjeQmqHFYUbDBTAmOSs8LIJDdFuyz1Y3kJqhxWFGxTAHwwIdHJhbnNmZXIMFM924ovQBixKR47jVWEBExnzz6TSQWJ9W1I5''
Inner exception:
InvalidOperationException: Collection was modified; enumeration operation may not execute.

This exception was originally thrown at this call stack:
    [External Code]
    Neo.VM.ReferenceCounter.CheckZeroReferred() in ReferenceCounter.cs
    Neo.VM.ExecutionEngine.PostExecuteInstruction() in ExecutionEngine.cs
    Neo.SmartContract.ApplicationEngine.PostExecuteInstruction() in ApplicationEngine.cs
    Neo.VM.ExecutionEngine.ExecuteNext() in ExecutionEngine.cs
```
Something failed here: https://github.com/neo-project/neo-vm/blob/a65487fa56be3eccb2c1dbfec5dcdd71b8a05fde/src/Neo.VM/StronglyConnectedComponents/Tarjan.cs#L93

**Comment by devhawk** [comment]
`s` on line 93 appears to be set on line 87:

https://github.com/neo-project/neo-vm/blob/a65487fa56be3eccb2c1dbfec5dcdd71b8a05fde/src/Neo.VM/StronglyConnectedComponents/Tarjan.cs#L87 

`StackItem.Successors` references the item's `ObjectReferences` dictionary

https://github.com/neo-project/neo-vm/blob/a65487fa56be3eccb2c1dbfec5dcdd71b8a05fde/src/Neo.VM/Types/StackItem.Vertex.cs#L31

The `ObjectReferences` dictionary can be modified in `ReferenceCounter.CheckZeroReferred`

https://github.com/neo-project/neo-vm/blob/a65487fa56be3eccb2c1dbfec5dcdd71b8a05fde/src/Neo.VM/ReferenceCounter.cs#L102-L106
