### ISSUE TITLE
v3.3.0 need more than 30 hours for syncing mainnet even it's just about 1.7million blocks

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-vm#481]
Syncing mode: offline import data from chain.0.acc
CPU: I7-10875H, 8 cores, 16 processors
Disk: 2TB SSD
RAM: 48GB
Cost time: More than 30 hours
Due to our investigation and several tests, something extremely lower the speed 5x ~ 10x for execution from https://github.com/neo-project/neo-vm/pull/471, revert it will make everything OK. But it's useful to prevent DDoS.
@devhawk @shargon @roman-khimov

**Comment by roman-khimov** [comment]
It's surprising to see this as the culprit, but the only other solution that comes to mind is just raising the NEWBUFFER price. Which I don't like also.
