### ISSUE TITLE
Set Operation in a Get Function

### ISSUE THREAD

**Issue by Liaojinghui** [neo-project/neo-vm#505]
https://github.com/neo-project/neo-vm/blob/5b0a39811b34abacab1273f3ee5a9a9f7e52ac7b/src/Neo.VM/Script.cs#L151

Code above is kind of weird, it `adds` objects into a Dictionary in a `Get` function.

**Comment by ixje** [comment]
it's caching the new instruction

**Comment by shargon** [comment]
It's for speed up the parsing time
