### ISSUE TITLE
New opcode 'PACKSTRUCT'

### ISSUE THREAD

**Issue by dicarlo2** [neo-project/neo-vm#51]
Like `PACK` but for structs.

**Comment by dicarlo2** [comment]
Without going into too much detail, we effectively store every value has an array of `[<number>, <value>]` in case we need to know the type at runtime[1]. Currently we store this as an array because it's relatively efficient to create:

```
// assume <value> is on stack
PUSH<number> // free
PUSH2 // free
PACK // 1 droplet
```

An equivalent struct is much more expensive to create, to the point that it's not feasible to use structs at all.

If we were able to use structs, then we could make other parts more efficient, for example, `===` becomes a simple `EQUAL` op, rather than needing to unwrap the value:
```
// assume two wrapped values are on the stack
PUSH1 // free
PICKITEM // 1 droplet
SWAP // 1 droplet
PUSH1 // free
PICKITEM // 1 droplet
EQUAL // 1 droplet
```

4x more efficient if we can use a struct and a single `EQUAL`. Another example scenario is using these wrapped values as keys in maps, this would preserve the semantics of JavaScript along with https://github.com/neo-project/neo-vm/issues/50. 

[1] Note, later iterations of neo-one will optimize this away when possible, but still in some cases we will need to continue wrapping.

**Comment by erikzhang** [comment]
Creating struct with `PACKSTRUCT`

```
PUSH value3
PUSH value2
PUSH value1
PUSH 3
PACKSTRUCT
```

Creating struct without `PACKSTRUCT`

```
PUSH 3
NEWSTRUCT
DUP
PUSH value1
APPEND
DUP
PUSH value2
APPEND
DUP
PUSH value3
APPEND
```

**Comment by anthdm** [comment]
@dicarlo2 Not sure why you should need that? Structs are treated the same as arrays. Their values are just an ordered union on the stack. The compiler should track all additional information about the underlying type and index of a field.

**Comment by dicarlo2** [comment]
@erikzhang do you have objections to adding `PACKSTRUCT`? This is blocking for NEO-ONE TypeScript smart contracts.
