### ISSUE TITLE
Script class crashes on `GetInstruction(i).Size`

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo-vm#517]
This is do to `GetInstruction(i).Size` crashes with `ERROR [22:57:16.400]    Index was outside the bounds of the array.`

https://github.com/neo-project/neo-vm/blob/426e54d560c311f4b9831bed763332d031c2dac2/src/Neo.VM/Script.cs#L77

```csharp
using var sb = new ScriptBuilder();
sb.Emit(OpCode.PUSHDATA1);

ExtensiblePayload payload = new()
{
    Category = "DDOS",
    Data = Array.Empty<byte>(),
    Sender = "NcScdqRaoE6DVzvGDBAnias9GTivdWfrDf".ToScriptHash(_ns.Settings.AddressVersion),
    ValidBlockStart = 0,
    ValidBlockEnd = NativeContract.Ledger.CurrentIndex(_ns.StoreView),
};

var col = Contract.CreateSignatureContract(ECPoint.Parse("034f7ea4ca4506ef288c5d5ed61686b9f39a0bc5f7670858305e32ea504ab543f3", ECCurve.Secp256r1));

payload.Witness = new Witness()
{
    InvocationScript = sb.ToArray(),
    VerificationScript = col.Script,
};
payload.VerifyWitnesses(_ns.Settings, _ns.GetSnapshot(), 0_06000000L) // Crashes
```

**Comment by Liaojinghui** [comment]
script wrong format

**Comment by cschuchardt88** [comment]
Yes but VerifyWitnesses shouldn't throw the exception, the VM should.

**Comment by Liaojinghui** [comment]
It indeed came from the vm

**Comment by Liaojinghui** [comment]
Ok, i understand what you mean vm throw exception now, yes, you are right

**Comment by shargon** [comment]
It's fault here https://github.com/neo-project/neo/blob/1ae6a13f8a269d8aecbf0f686330d56db72accfc/src/Neo/SmartContract/Helper.cs#L316 isn't it?

**Comment by shargon** [comment]
> Ok, i understand what you mean vm throw exception now, yes, you are right. I will catch the exception in the vm after we processed the mono repo.

We still waiting for the tests and release 3.6.2, we can't fix this during that time.

**Comment by cschuchardt88** [comment]
>It's fault here https://github.com/neo-project/neo/blob/1ae6a13f8a269d8aecbf0f686330d56db72accfc/src/Neo/SmartContract/Helper.cs#L316 isn't it?

Yes that would be correct.
