### ISSUE TITLE
Allow array of single value to pass CHECKSIG

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo-vm#54]
Guys, do you think that's ok to change line https://github.com/neo-project/neo-vm/blob/ab5f939529eb7527f08b36949269ffd171821f03/src/neo-vm/ExecutionEngine.cs#L588 to accept a array of single value (single signature) to be accepted by CHECKSIG?
The idea is that we could use the exactly same mechanism for single sigs and multi sigs, that can simplify a few things. Something like this:

https://github.com/neo-project/neo-vm/blob/master/src/neo-vm/ExecutionEngine.cs#L618-L619

 I can make the PR, just wondering if that's too crazy :)

**Comment by shargon** [comment]
Do you want to unify CHEKSIG and CHECKMULTISIG?

**Comment by ixje** [comment]
I think thats the idea, but that would increase execution time for all regular `CHECKSIG` calls as there are far more sanity checks going on in `CHECKMULTISIG` and also more stack manipulations. @igormcoelho what exact benefits do you foresee this would have?

**Comment by igormcoelho** [comment]
@shargon in fact, I don't want to unify, because the "canonical" (or standard) structure of a CHECKSIG is more simple than CHECKMULTISIG, and this expects more parameters. What I want to do is to allow CHECKSIG to succeed if user passes the following invocation script:
```
PUSH40 ... SIGNATURE
PUSH1 
PACK
```
@ixje The advantage I see is that all standard verification scripts could naturally expect arrays as input. The benefits could be seen easily in our NEO-SMACCO composer (that creates smart accounts based on simple json): http://neoresearch.io/smacco-demo/
Currently, we need two basis (single input and array input), but if CHECKSIG accepts single array, all this logic will be drastically simplified.

**Comment by igormcoelho** [comment]
Ok, I implemented the feature hahaha easier to discuss with an implementation proposal ;)
Do you see any downsides related to this? Any attacks? I don't see any...

**Comment by ixje** [comment]
the example implementation was helpful to clarify the intention. I left my comments there.

**Comment by erikzhang** [comment]
Agree with @ixje.

On the other hand, I have plans to remove `CHECKSIG` and `CHECKMULTISIG` from NeoVM in NEO 3.0.

**Comment by igormcoelho** [comment]
@ixje thanks a lot for the comments.
@erikzhang, I fully agree that CHECKSIG could be in a higher layer, because it depends on GetMessage, and that always confused me (I took a long time to understand what was going on). On the other hand, this change is more related to a standard view than CHECKSIG itself... even if CHECKSIG changes to anything else, I guess the logic of submitting signature and validating will be kept intact, am I correct?
And in terms of signature validation, it would be nice to have a standard... this change here allows an implicit standard to happen:
`bool Main(Signature[] sigs) { ... }`
It's similar to the general Application standard (with string, object[]), but for Signature Redeem Scripts on general. By the way, I guess we could have a `Signature` object on devpack, to enforce byte[] with a fixed number of bytes... that makes things even more clear ;)

**Comment by shargon** [comment]
This opcodes will be syscalls? @erikzhang

**Comment by erikzhang** [comment]
We can use `VERIFY` instead.

https://github.com/neo-project/neo-vm/blob/94a91ae63b95ee49c58c6d7468fa766637999c07/src/neo-vm/OpCode.cs#L382

According to my plan, in NEO 3.0, all contracts will have a uniform entry point for all triggers:

```c#
object Main(string operation, object[] args)
```

For `Verification` trigger, the `operation` should be `"verify"`, the `args[0]` should be the transaction itself, the `args[1]` should be a byte array that contains the result from old `GetMessage()`, and the `args[2]` is the signature.

So the system will trigger the contract like this:

```c#
verify(tx, message, signature);
```

The `verify` method can be implemented with the `VERIFY` opcode:

```c#
bool verify(Transaction tx, byte[] message, byte[] signature)
{
    byte[] pubkey = {};
    return OpCodes.VERIFY(message, signature, pubkey);
}
```

**Comment by igormcoelho** [comment]
The plan is good @erikzhang ! I just think we don't need to pass the transaction or the message itself by parameters, as they could be accessible already on ApplicationEngine. May I suggest the operation `System.Transaction.GetMessage`? I was already sure that existed hahaha but it doesn't... using this operation I could build `GetMessage()`, and it's easy to build this way:
```cs
object Main(string operation, object[] args) {
    return (operation=="verify") && (args.Length==1) && verify((byte[])args[0], GetMessage(), pubkey_x);
}
```

So, if you allow me to go even deeper, I guess `CHECKSIG` should start accepting this format too, so wallets will be fully prepared for the future.

**Comment by igormcoelho** [comment]
I created a proposed "verify" validation that would work in your current proposal Erik. I will take last parameter from args as if it was the signature, so even if things change regarding the first two system parameters (tx and message), it will work anyway.

**Comment by erikzhang** [comment]
Let me organize the steps:

First, the wallet provides a signature or other parameters in `Witness.InvocationScript`:

```
PUSH <signature>
```

When other nodes verify the transaction, they need to perform an additional packaging operation on the items in the stack and push `"verify"` into the stack:

```
DEPTH
PACK
PUSH "verify"
```

After that, the node should execute `Witness.VerificationScript`, so it should be:

```
DROP
UNPACK
DROP
SYSCALL System.Runtime.GetScriptContainer
SYSCALL System.ScriptContainer.GetMessage
SWAP
PUSH <pubkey>
VERIFY
```

It may seem a bit verbose and may need to be optimized.

**Comment by igormcoelho** [comment]
Sorry about the rush coding Erik hahaha I was just giving an example to clarify the discussion :)
I think both ways are good Erik, but if you prefer to do that in the future, we can take that easy for now ;) In my opinion, the decision to think about is that if we want to have scripts not appearing on Invocation or Verification, because this middle (automatic) part won't be recorded to the blockchain, right? I really like this format where Invocation+Verification forms a complete script, so it would be nice to keep this. If you want to enforce the canonical format using `Main(string, object[])`, then I would prefer to have user sending this invocation:
```
PUSH <signature> //stack: <signature>
DEPTH         //stack: <signature>, 1
PACK          //stack: [<signature>]
PUSH "verify" //stack: [<signature>], "verify"
```
And nodes verify that top stack items are: bytearray and array, respectively, otherwise it fails execution automatically. Then the rest could be done in verification script itself. It would be also nice to have `SYSCALL System.Runtime.GetMessage`.

**Comment by erikzhang** [comment]
Invocation:

```
PUSH <signature> //stack: <signature>
DEPTH            //stack: <signature>, 1
PACK             //stack: [<signature>]
PUSH "verify"    //stack: [<signature>], "verify"
```

Verification:

```
DROP                              //stack: [<signature>]
UNPACK                            //stack: <signature>, 1
DROP                              //stack: <signature>
SYSCALL System.Runtime.GetMessage //stack: <signature>, <message>
SWAP                              //stack: <message>, <signature>
PUSH <pubkey>                     //stack: <message>, <signature>, <pubkey>
VERIFY                            //stack: <true|false>
```

This looks perfect except that the `VerificationScript` is much longer than it used to be. 😄

**Comment by igormcoelho** [comment]
Very good Erik! This is a nice format! Some time ago I did some proposal for us to allow hashing the names of interop functions.... if we adopt 8 bytes it could cut some space in many applications.
Example: `System.Runtime.GetMessage` has 25 bytes: `53797374656d2e52756e74696d652e4765744d657373616765`
First 8 bytes of single SHA256 is: `a59207ee04ce1a23`, so we could do: SYSCALL a59207ee04ce1a23. It's a strange solution tough, but it compress data ;)

**Comment by erikzhang** [comment]
Maybe we should implement this proposal first: https://github.com/neo-project/neo/issues/264

**Comment by igormcoelho** [comment]
Now it's neo-project/neo related.
