### ISSUE TITLE
Improve PACK/UNPACK opcodes

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo-vm#59]
[EDIT] The initial ideia was to create a new opcode called `CONVERT`. Then, after discussions with @shargon , I changed to a new direction, without creating any new opcode, just updating PACK and UNPACK.

=====

I think three different problems can be solved by having an opcode capable of converting byte[] to Array (of byte) and back.

1) REVERT only works on Array types: https://github.com/neo-project/neo-vm/issues/17
2) SETITEM only works on Array types: https://github.com/neo-project/neo-vm/issues/58
3) SIZE and ARRAYSIZE with be redundant: https://github.com/neo-project/neo-vm/blob/master/src/neo-vm/OpCode.cs

The idea of this opcode CONVERT is to allow a convertion between a reference type Array to a static type bytearray, and to allow byte[] to have easy use of operations that are available for arrays. All these operations could be done in high level, however, at a big cost of opcodes, and higher code complexity. Using this opcode, REVERSE could be easily done:

```
PUSH10 ababababab...
CONVERT # converts byte[] to Array (of byte) on stack
DUP # duplicates Array on stack
REVERSE  # reverse and drop array
CONVERT  # convert Array back to byte[] on stack
```

SETITEM will work in the same way.

Opcode SIZE could be easily replaced by ARRAYSIZE (as proposed by Erik on https://github.com/neo-project/neo-vm/pull/57).

```
PUSH10 ababababab...
CONVERT # converts byte[] to Array (of byte) on stack
DUP # duplicates Array on stack
ARRAYSIZE # removes Array and puts its size on stack
```

```cs
/// <summary>
/// A bytearray or array (of byte) is taken from the stack. If bytearray is taken, an array with the same bytes is put on stack. If Array is taken, a bytearray is created with the exact size, having each element transferred from one to another.
/// </summary>
CONVERT = 0xCE,
```

**Comment by shargon** [comment]
Can we use `UNPACK` ?

**Comment by igormcoelho** [comment]
Very goooooood Shargon! Now it's better... we just use `CONVERT` and then use `UNPACK`.

**Comment by igormcoelho** [comment]
> Can we use `UNPACK` ?

Now I got your point Shargon!! I think `UNPACK` is good to work as a conversor from ByteArray to Array:
https://github.com/neo-project/neo-vm/blob/master/src/neo-vm/ExecutionEngine.cs#L713-L719

**Comment by igormcoelho** [comment]
Now I think this breaks semantics, and we have much better options for Neo3.
