### ISSUE TITLE
Clone structs on `PICKITEM`

### ISSUE THREAD

**Issue by dicarlo2** [neo-project/neo-vm#63]
We use structs heavily in NEO-ONE TypeScript smart contracts and we depend on the fact that structs are cloned from `PICKITEM`. So, we'd like to implement https://github.com/neo-project/neo-vm/pull/49 again, however this time with a simple logic switch such that old contracts use the old buggy behavior and new contracts use the corrected behavior.

Ideally, we could just turn this feature on using the height the contract was created at, but we don't store this information anywhere. So we'll need an alternate way to determine if a given contract should use the new behavior or old. I suggest that we add a new contract property similar to payable, dynamic invoke, etc. which when present means that the contract uses the new behavior.

This is blocking for NEO-ONE TypeScript smart contracts.

**Comment by erikzhang** [comment]
`PICKITEM` should not clone the struct.

Let's say we have an array `A[]`, and a struct `B[]`. We append `B` to `A`, so we get `A[B]`.

Then we use the `PICKITEM` to push `B` onto the stack and try to modity it. But `B` is a struct, if we clone it, we will never be able to modify its value.

I describe this scenario in C#:

```c#
struct TestStruct
{
    public int Field1;
    public int Field2;
}

void Main()
{
    TestStruct[] array = { new TestStruct() };
    array[0].Field1 = 100; //It's impossible if `PICKITEM` clone the struct
}
```
