### ISSUE TITLE
InteropInterface

### ISSUE THREAD

**Issue by shargon** [neo-project/neo-vm#65]
At now `InteropInterface` just accept `IInteropInterface`  objects, but this cause a problem if you want to change the VM, because you can't share the same `InteropService` . This interface is defined inside the VM package, so we can't reuse the same `InteropService` for different implementations of the VM. 

If we change this to a native object, or just accept any object, all should works for both scenarios

**Comment by erikzhang** [comment]
Why we need different VMs?

**Comment by shargon** [comment]
Not different VM, but the same VM with different implementations, for easy benchmarking, for example HyperVM (c++) and this one

Closed by #67
