### ISSUE TITLE
Create CONVERT opcode

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo-vm#70]
Dear all, I've been thinking on this for a while, and I think now that a single new opcode can help solving many different issues. 

I propose the creation of a new opcode, `CONVERT <type>`, that receives a byte `<type>` indicating the conversion type and converts element that is on top stack (putting the converted element on stack). I initially propose the following types:
```
0x00: ByteArray
0x01: Array
0x02: Integer
0x03: Struct
0x04: Map
0x05: Boolean
...
0x80: Clone
```

Applications:

1) we could REVERSE for bytearrays (opened at https://github.com/neo-project/neo-vm/issues/17 and currently solved on PR https://github.com/neo-project/neo-devpack-dotnet/pull/37, but could be much more efficient):
```
PUSH_bytearray
CONVERT 0x01 # convert to array
DUP
REVERSE
CONVERT 0x00 # convert to bytearray
```

2) We could perhaps transform array into structs and solve this: https://github.com/neo-project/neo-vm/issues/51
`CONVERT 0x03 # convert stack array to struct`

3) We could transform bytearrays to integers and guarantee that they would follow BigInteger standard (by summing zero for example).
`CONVERT 0x02 # convert to biginteger`

4) We could convert maps and arrays, so repeated opcodes could be eliminated (including bytearray/array sizes, appends, ...)
`CONVERT 0x01 # convert to array and get length`
`ARRAYSIZE`

5) We could do an efficient concatenation of array elements by transforming array to bytearray
`PUSH ...`
`PUSH ...`
`CAT`
`PUSH ...`
`CAT`
`####`
`PUSH ...`
`NEWARRAY`
`CONVERT 0x00 # convert to bytearray`

6) We could perhaps add a CLONE type in conversion(`0x80 + 0x03`), so we could choose to convert into a new one or an actual clone (and help solving this https://github.com/neo-project/neo-vm/issues/63)
`CONVERT 0x83 # convert to cloned struct`

7) We could avoid this PACK/UNPACK workaround: https://github.com/neo-project/neo-vm/pull/60
`CONVERT 0x01 # convert to array and assign value`
` ... assign ...`
`CONVERT 0x00 # convert back to bytearray`

8) We can use it to enforce alternative types such as Boolean and Byte (even if stored as bytearray).
`PUSH5`
`CONVERT 0x05 # to boolean (true if not zero)`

Perhaps this feature could antecipate issues and bring many future possibilities on Neo 3.0 (and removing many unused opcodes), just by having a direct conversion tool for StackItems.

**Comment by igormcoelho** [comment]
Any thoughts @dicarlo2 @shargon ?

**Comment by shargon** [comment]
At the end, the others OpCodes make the conversion, so i don't get the point 😅

For example: When `MUL` receive a `Bool` or `ByteArray`, it's converted to `BigInteger`

**Comment by igormcoelho** [comment]
Man, I gave you 8 situations where no conversion exists xD

**Comment by lightszero** [comment]
still need compiler，so what code can use that convert？ show some case maybe.

**Comment by igormcoelho** [comment]
I think that this can be done together with the `CLONE` idea @lightszero ... perhaps a `CloneAs` that chooses the selected type after conversion.
