### ISSUE TITLE
Move GAS cost and Limits to neoVM

### ISSUE THREAD

**Issue by shargon** [neo-project/neo-vm#73]
I want to move the limits (stack,BigInteger..) and Gas costs from ApplicationEngine to this project, NeoVM.

Benficts:

- This could help with unit testing in this project
- Speed up the VM because we need to check twice now
- Centralize the VM procedures
- Help projects that want to use the official neoVM with the current configuration.

If someone want to use the NeoVM, with other limits, they could configure before use it according to his necessities.

**Comment by erikzhang** [comment]
At the beginning, GAS costs were calculated in NeoVM. Later, considering the portability of NeoVM, it was moved from NeoVM to the NeoContract layer.

**Comment by shargon** [comment]
I think that NeoVM should contains all related to the VM, and configure it according to the necessities, otherwise we have to review twice the same information.

**Comment by erikzhang** [comment]
Can you give an example of which information has been reviewed twice?

**Comment by shargon** [comment]
We have more than two `switch`s, more than one in `ApplicationEngine` for limits (Stack, BigInteger, etc..) and other for gas, then.. in `ExecutionEngine` we have the primary one in `StepInto` for execute the opcodes, i want to avoid any opcode `switch` inside the `ApplicationEngine`, and move all of this logic in `ExecutionEngine`.

**Comment by shargon** [comment]
we can made GAS cost virtual as well

**Comment by igormcoelho** [comment]
It would be nice to have a NeoVM version without GAS limits too, because GAS itself is a concept connected to NeoContract... but it's possible to exist other NeoVM implementations without any GAS concept. For industrial private networks based on Neo, for instance. Anyway, the more general parameters embedded in NeoVM it's better indeed.

**Comment by erikzhang** [comment]
I think NeoVM should be made into a pure virtual machine, so the concept of GAS should not appear in virtual machines.

**Comment by vncoelho** [comment]
I also agree, I prefer the NEO-VM isolated without the concept of GAS.

**Comment by shargon** [comment]
For me have no sense process the opcodes twice, one for compute the GAS, and other for execution

**Comment by vncoelho** [comment]
I got the point, Shargon, but it is just a O(1) acess to its costs, right?
