### ISSUE TITLE
Add releases

### ISSUE THREAD

**Issue by ixje** [neo-project/neo-vm#93]
Can we start adding release tags for this repo as well? It's becoming hard to know which commits work with which `neo-cli` version. Like now I want to crosscheck RPC output against `neo-cli` `2.10.0.0` after all the VM updates but that still returns multiple engine states as if it still were flags.
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "script": "00c1046e616d6567c2563cdd3312230722820b1681d30fe5f6cffbb9",
        "state": "HALT, BREAK",
        "gas_consumed": "0.128",
        "stack": [
            {
                "type": "ByteArray",
                "value": "4e45582054656d706c617465205632"
            }
        ]
    }
}
```

**Comment by ixje** [comment]
fyi; this is basically a request similar to this old issue https://github.com/neo-project/neo-vm/issues/43

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo-vm/tags

Done.

**Comment by ixje** [comment]
Thanks! I think that's all for this issue
